const express = require('express');
const router = express.Router();
const { pool } = require('../db');
const { authenticate, authorize } = require('../middleware/auth');

// Get all inventory items
router.get('/items', authenticate, async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT i.*, bi.quantity as current_stock
       FROM inventory_items i
       LEFT JOIN branch_inventory bi ON i.id = bi.item_id AND bi.branch = $1
       ORDER BY i.item_code`,
      [req.query.branch || 'Bomet']
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching inventory items:', error);
    res.status(500).json({ error: 'Failed to fetch inventory items' });
  }
});

// Get single inventory item details
router.get('/items/:id', authenticate, async (req, res) => {
  try {
    // Get basic item details
    const itemResult = await pool.query(
      `SELECT * FROM inventory_items WHERE id = $1`,
      [req.params.id]
    );

    if (itemResult.rows.length === 0) {
      return res.status(404).json({ error: 'Item not found' });
    }

    // Get stock by branch
    const stockResult = await pool.query(
      `SELECT branch, quantity 
       FROM branch_inventory 
       WHERE item_id = $1`,
      [req.params.id]
    );

    const item = itemResult.rows[0];
    item.stock_by_branch = stockResult.rows;
    item.total_stock = stockResult.rows.reduce((sum, row) => sum + row.quantity, 0);

    res.json(item);
  } catch (error) {
    console.error('Error fetching item details:', error);
    res.status(500).json({ error: 'Failed to fetch item details' });
  }
});

// Get full history (adjustments, transfers, purchases, etc.)
router.get('/items/:id/history-full', authenticate, async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT id, 'adjustment' as type, quantity, branch, notes, created_at, created_by 
       FROM inventory_adjustments WHERE item_id = $1
       UNION ALL
       SELECT id, 'transfer_out' as type, -quantity as quantity, from_branch as branch, notes, created_at, requested_by as created_by
       FROM stock_transfers st JOIN stock_transfer_items sti ON st.id = sti.transfer_id 
       WHERE sti.item_id = $1 AND st.status = 'approved'
       UNION ALL
       SELECT id, 'transfer_in' as type, quantity, to_branch as branch, notes, created_at, requested_by as created_by
       FROM stock_transfers st JOIN stock_transfer_items sti ON st.id = sti.transfer_id 
       WHERE sti.item_id = $1 AND st.status = 'approved'
       UNION ALL
       SELECT id, 'purchase' as type, quantity, branch, notes, created_at, created_by
       FROM purchase_orders po JOIN purchase_order_items poi ON po.id = poi.po_id
       WHERE poi.item_id = $1 AND po.status = 'received'
       ORDER BY created_at DESC`,
      [req.params.id]
    );

    // Enrich with user emails
    for (let row of result.rows) {
      if (row.created_by) {
        const userRes = await pool.query('SELECT email FROM users WHERE id = $1', [row.created_by]);
        row.created_by_email = userRes.rows[0]?.email || 'Unknown';
      }
    }

    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching item history:', error);
    res.status(500).json({ error: 'Failed to fetch item history' });
  }
});

// Create inventory item
router.post('/items', authenticate, authorize(['super_admin', 'manager', 'storekeeper']), async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    
    const {
      name,
      category,
      subcategory,
      unit,
      reorder_level,
      branches,
      description
    } = req.body;

    // Insert item (item_code will be auto-generated by trigger)
    const itemResult = await client.query(
      `INSERT INTO inventory_items (name, category, subcategory, unit, reorder_level, description, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING id, item_code`,
      [name, category, subcategory, unit, reorder_level, description, req.user.id]
    );

    // Initialize stock levels for each branch
    for (const branch of branches) {
      await client.query(
        `INSERT INTO branch_inventory (item_id, branch, quantity)
         VALUES ($1, $2, 0)`,
        [itemResult.rows[0].id, branch]
      );
    }

    await client.query('COMMIT');
    res.status(201).json(itemResult.rows[0]);
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error creating inventory item:', error);
    res.status(500).json({ error: 'Failed to create inventory item' });
  } finally {
    client.release();
  }
});

// Update inventory item
router.put('/items/:id', authenticate, authorize(['super_admin', 'manager', 'storekeeper']), async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    
    const {
      name,
      category,
      subcategory,
      unit,
      reorder_level,
      description
    } = req.body;

    const result = await client.query(
      `UPDATE inventory_items
       SET name = $1, category = $2, subcategory = $3, unit = $4,
           reorder_level = $5, description = $6, updated_at = NOW()
       WHERE id = $7
       RETURNING *`,
      [name, category, subcategory, unit, reorder_level, description, req.params.id]
    );

    await client.query('COMMIT');
    res.json(result.rows[0]);
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error updating inventory item:', error);
    res.status(500).json({ error: 'Failed to update inventory item' });
  } finally {
    client.release();
  }
});

// Update stock level
router.post('/items/:id/stock', authenticate, authorize(['super_admin', 'manager', 'storekeeper']), async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    
    const { branch, quantity, adjustment_type, notes } = req.body;

    // Update stock level
    await client.query(
      `UPDATE branch_inventory
       SET quantity = CASE
         WHEN $1 = 'add' THEN quantity + $2
         WHEN $1 = 'subtract' THEN GREATEST(0, quantity - $2)
         ELSE $2
       END
       WHERE item_id = $3 AND branch = $4`,
      [adjustment_type, quantity, req.params.id, branch]
    );

    // Record adjustment
    await client.query(
      `INSERT INTO inventory_adjustments (item_id, branch, quantity, adjustment_type, notes, created_by)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [req.params.id, branch, quantity, adjustment_type, notes, req.user.id]
    );

    await client.query('COMMIT');
    res.json({ message: 'Stock level updated successfully' });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error updating stock level:', error);
    res.status(500).json({ error: 'Failed to update stock level' });
  } finally {
    client.release();
  }
});

// Get stock history
router.get('/items/:id/history', authenticate, async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT ia.*, u.email as adjusted_by
       FROM inventory_adjustments ia
       LEFT JOIN users u ON ia.created_by = u.id
       WHERE ia.item_id = $1
       ORDER BY ia.created_at DESC`,
      [req.params.id]
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching stock history:', error);
    res.status(500).json({ error: 'Failed to fetch stock history' });
  }
});

// Get low stock items
router.get('/low-stock', authenticate, authorize(['super_admin', 'manager', 'storekeeper']), async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT i.*, bi.branch, bi.quantity as current_stock
       FROM inventory_items i
       JOIN branch_inventory bi ON i.id = bi.item_id
       WHERE bi.quantity <= i.reorder_level
       ORDER BY bi.branch, i.category, i.name`
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching low stock items:', error);
    res.status(500).json({ error: 'Failed to fetch low stock items' });
  }
});

// Get stock transfer history
router.get('/transfers', authenticate, async (req, res) => {
  try {
    const result = await pool.query(
      `SELECT st.*, 
              u1.email as requested_by_user,
              u2.email as approved_by_user,
              i.name as item_name,
              i.item_code
       FROM stock_transfers st
       JOIN stock_transfer_items sti ON st.id = sti.transfer_id
       JOIN inventory_items i ON sti.item_id = i.id
       LEFT JOIN users u1 ON st.requested_by = u1.id
       LEFT JOIN users u2 ON st.approved_by = u2.id
       ORDER BY st.created_at DESC`
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Error fetching transfer history:', error);
    res.status(500).json({ error: 'Failed to fetch transfer history' });
  }
});

// Create stock transfer
router.post('/transfers', authenticate, authorize(['super_admin', 'manager', 'storekeeper']), async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    
    const { from_branch, to_branch, items, notes } = req.body;

    const transferResult = await client.query(
      `INSERT INTO stock_transfers (from_branch, to_branch, notes, requested_by)
       VALUES ($1, $2, $3, $4)
       RETURNING id`,
      [from_branch, to_branch, notes, req.user.id]
    );

    const transferId = transferResult.rows[0].id;

    for (const item of items) {
      await client.query(
        `INSERT INTO stock_transfer_items (transfer_id, item_id, quantity)
         VALUES ($1, $2, $3)`,
        [transferId, item.item_id, item.quantity]
      );
    }

    await client.query('COMMIT');
    res.status(201).json({ id: transferId });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error creating stock transfer:', error);
    res.status(500).json({ error: 'Failed to create stock transfer' });
  } finally {
    client.release();
  }
});

// Approve stock transfer
router.post('/transfers/:id/approve', authenticate, authorize(['super_admin', 'manager']), async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    
    // Update transfer status
    await client.query(
      `UPDATE stock_transfers
       SET status = 'approved', approved_by = $1, approved_at = NOW()
       WHERE id = $2`,
      [req.user.id, req.params.id]
    );

    // Get transfer details
    const transfer = await client.query(
      `SELECT * FROM stock_transfers WHERE id = $1`,
      [req.params.id]
    );

    // Update stock levels
    const items = await client.query(
      `SELECT * FROM stock_transfer_items WHERE transfer_id = $1`,
      [req.params.id]
    );

    for (const item of items.rows) {
      // Reduce stock at source branch
      await client.query(
        `UPDATE branch_inventory
         SET quantity = quantity - $1
         WHERE item_id = $2 AND branch = $3`,
        [item.quantity, item.item_id, transfer.rows[0].from_branch]
      );

      // Increase stock at destination branch
      await client.query(
        `UPDATE branch_inventory
         SET quantity = quantity + $1
         WHERE item_id = $2 AND branch = $3`,
        [item.quantity, item.item_id, transfer.rows[0].to_branch]
      );
    }

    await client.query('COMMIT');
    res.json({ message: 'Stock transfer approved successfully' });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error approving stock transfer:', error);
    res.status(500).json({ error: 'Failed to approve stock transfer' });
  } finally {
    client.release();
  }
});

module.exports = router;
