-- =====================================================================
-- FAMOUSGATE MAJOR REDESIGN — 2026-06-22
-- DO NOT AUTO-RUN. Copy into the Supabase SQL Editor for manual review.
--
-- IMPORTANT — READ BEFORE RUNNING:
-- This file was hand-written against the LIVE schema (backend/database-schema.live.json,
-- backend/database-schema.json, and the actual migration history under
-- backend/migrations/ and backend/supabase/migrations/), not against the assumed
-- names in the original request. Several requested table/column names do not exist
-- in production; where a real equivalent exists, this migration targets the real
-- table and documents the substitution. Every deviation from the literal request is
-- marked with a "DEVIATION:" comment so you can veto it before running.
--
-- Key deviations up front:
--   * `daily_financial_close` does not exist. The live equivalent is
--     `daily_financial_records` (backend/supabase/migrations/72_financial_workspace_tables.sql).
--   * `branch_id` is INTEGER everywhere in this schema (branches.id is an int4 sequence),
--     not UUID. Every new FK to branches(id) below uses INTEGER, correcting the
--     request's UUID assumption.
--   * `cashier_shift_payments` does not exist. The live table that already stores
--     per-payment-method rows per shift is `cashier_shift_transactions`
--     (shift_id, transaction_id, payment_method, amount). Using it instead of creating
--     a duplicate parallel table.
--   * `outbound_payments` does not exist either — the live table for branch outbound
--     cash payments is `branch_payments` (backend/migrations/20260611_branch_payments.sql),
--     which already has a full maker-checker approval workflow: `category` is
--     vendor|petty_cash|inter_branch|staff_payout|utility|other and `status` is
--     pending|manager_approved|director_approved|released|rejected. Re-applying the
--     request's literal CHECK (category IN ('daily_purchase','petty_cash','transaction_cost'))
--     and CHECK (status IN ('pending','settled')) onto those EXISTING columns would
--     reject every row already sitting in manager_approved/director_approved/released/
--     rejected/vendor/inter_branch/staff_payout/utility states — i.e. it would break the
--     live approval workflow outright. Instead, two NEW, non-colliding columns are added:
--     `cash_flow_category` and `settlement_status`, carrying the requested vocabulary
--     for P&L purposes without touching the existing approval-workflow columns. A new
--     `purchase_order_id` FK is also added rather than reusing the existing generic
--     `po_id` column, since `po_id` is shared three-way-match bookkeeping (po/grn/invoice)
--     for manually-created payments, not specifically "this row was auto-generated by
--     the cash-PO trigger."
--   * `stock_out_lines` does not exist. The live "stock out" ledger is
--     `stock_out_records` (backend/src/database/migrations/20231201_simple_stock_management.sql),
--     keyed by item_sku (text), not item_id.
--   * The generic `payments` table found in the live schema is a hotel
--     booking/folio payments table (booking_id, folio_id) — unrelated to
--     cashier/POS shift payments and has no shift_id/pos_transaction_id columns.
--     Section 7's dedup target has been moved to `cashier_shift_transactions`,
--     which is the table that actually has the shape described in the request.
--   * (SUPERSEDED — see "LIVE-DATABASE VERIFICATION PASS" below) `inventory_items.id`
--     was originally assumed to be INTEGER; it is actually UUID.
--   * (SUPERSEDED — see "LIVE-DATABASE VERIFICATION PASS" below) Receive-goods
--     lines were originally assumed to be `grn_items`/`goods_received_notes`;
--     those tables don't exist. Real tables: store_grn_items/store_grn and
--     goods_receipt_lines/goods_receipts.
--   * The original section-4 trigger was declared AFTER INSERT but tried to set
--     NEW.is_daily_expense inside the function body. In Postgres, mutating NEW in
--     an AFTER trigger has no effect on the stored row (the row is already
--     committed by the time AFTER triggers fire). Corrected to BEFORE INSERT so
--     the flag actually persists; NEW.id is still available pre-insert because
--     column defaults (gen_random_uuid()) resolve before BEFORE triggers run.
--
-- LIVE-DATABASE VERIFICATION PASS (everything below was confirmed against the
-- actual running Postgres instance via information_schema after the first
-- attempt to run this file failed — backend/database-schema.json turned out to
-- be a stale snapshot and is no longer trusted for types in this file):
--   * `inventory_items.id` is UUID, not INTEGER as the snapshot claimed. Every
--     new FK to inventory_items(id) below (sections 9, 10, 11, 12) is UUID.
--   * `purchase_orders.branch_id` is a real, existing INTEGER column — there is
--     no `receiving_branch_id`. The original section-4 fix to "receiving_branch_id"
--     was itself wrong (guessed from the same stale snapshot); reverted to the
--     real `branch_id`.
--   * `purchase_orders` has no `supplier_name` column, and the app actually
--     writes `created_by_id` (not `created_by` — confirmed by an explicit
--     comment in backend/src/controllers/storekeeping/purchase-orders.controller.ts:470,
--     "Override created_by_id with the correct field name"). Section 4 now
--     reads NEW.created_by_id and resolves the payee name via a `suppliers`
--     lookup on NEW.supplier_id (suppliers.name confirmed to exist).
--   * `grn_items` and `goods_received_notes` (used in the original section 2/10
--     drafts) do not exist anywhere in this database — that migration file was
--     apparently never applied. The real receiving tables are
--     `goods_receipts`/`goods_receipt_lines`. (An earlier pass of this file also
--     queried `store_grn`/`store_grn_items` as if they were a second, separate
--     receiving flow — they are not. Confirmed via pg_views: both are plain,
--     unfiltered passthrough VIEWs — `store_grn` is exactly
--     `SELECT <cols> FROM goods_receipts` and `store_grn_items` is exactly
--     `SELECT <cols> FROM goods_receipt_lines`, no WHERE clause or
--     transformation. Summing both would have double-counted every received
--     line in the P&L COGS figure, and Postgres outright refuses to create a
--     row-level trigger on a view at all — so section 2 and section 10 below
--     query/trigger ONLY the real base tables.)
--   * `stock_out_records` is ALSO a view, not a base table — but unlike
--     store_grn_items it is NOT a simple passthrough. It's a filtered,
--     three-table-joined view: roughly `SELECT ... FROM branch_stock_movements
--     bsm LEFT JOIN branch_stock bs ... LEFT JOIN simple_items si ... WHERE
--     (bsm.quantity < 0) OR (lower(bsm.movement_type) IN ('stock_out','out',
--     'issue','department_issue','pos_issue','kitchen_issue','usage'))`, with
--     `quantity` exposed as `abs(bsm.quantity)`. So the real base table is
--     `branch_stock_movements`, which stores BOTH stock-in and stock-out
--     movements with a SIGNED quantity (negative for outs) — and it already
--     has its own `item_id UUID` column directly (confirmed via
--     information_schema), so the item_code/item_sku lookup used in earlier
--     drafts of this file is now only a fallback, not the primary path.
--     Sections 10 and 13 below attach their triggers to branch_stock_movements
--     (the real table) and each replicates the view's exact "is this an
--     out-movement" predicate as a guard, since a trigger on the base table
--     fires for stock-IN rows too and must not misfire on those. Section 2's
--     operational-expense query reads branch_stock_movements directly rather
--     than through the view, since the view's SELECT list doesn't expose the
--     new is_operational_expense/line_cost columns and this migration
--     deliberately leaves the existing view untouched for any other
--     consumers relying on its current shape.
-- =====================================================================


-- =====================================================================
-- 1. DAILY FINANCIAL CLOSE ISOLATION
--    Real table: daily_financial_records (backend/supabase/migrations/72_financial_workspace_tables.sql)
--    Audit result: no SQL VIEW, RPC, or FUNCTION was found joining this table
--    into P&L/analytics/overview/revenue queries. The only SQL-level consumer is
--    `branch_profitability_summary` (backend/src/database/migrations/20260613_financial_governance.sql),
--    which selects ONLY from daily_financial_records — that is its own dedicated
--    fetch, not a join-in, so it is left untouched.
--
--    NOTE (outside SQL scope — flagging, not fixing here): backend/src/controllers/
--    director.controller.ts and director-enhanced.controller.ts read
--    daily_financial_records directly via the Supabase client (getFinancialMetrics,
--    getVisualData, getBankingControl, getPaymentIntelligence, getPaymentBreakdown,
--    getBankingReconciliation) for Director-dashboard analytics. These are
--    application-layer reads, not SQL joins, so a SQL migration cannot isolate
--    them. Recommend a follow-up code review of those controllers if the intent
--    is to fully wall this table off from blended analytics.
-- =====================================================================

-- ISOLATED: This table must never be joined into P&L, analytics, overview, or revenue queries
COMMENT ON TABLE daily_financial_records IS
  'ISOLATED: This table must never be joined into P&L, analytics, overview, or revenue queries. It is the accountant''s manually-submitted daily close record. Read it only via its own dedicated fetch (see backend/src/controllers/financial-close.controller.ts / financial-workspace.controller.ts).';


-- =====================================================================
-- 2. PROFIT & LOSS AGGREGATION RPC
--    DEVIATION: branch_id parameter is INTEGER (branches.id is int4), not UUID.
--    DEVIATION: sources cashier_shift_transactions instead of the nonexistent
--    cashier_shift_payments (see header note).
--    DEVIATION: COGS sourced from goods_receipt_lines+goods_receipts (the real
--    base tables — see header note; grn_items/goods_received_notes do not
--    exist, and store_grn/store_grn_items are just views over these same two
--    tables, so they are NOT also summed — that would double-count).
--    DEVIATION: "Stock out lines where is_operational_expense = true" reads
--    branch_stock_movements directly (the real base table behind the
--    stock_out_records view — see header note), filtered to out-movements
--    only via the same predicate the view uses.
--    DEVIATION: "outbound_payments filtered by branch_id and date range, grouped
--    by category" reads from `branch_payments.cash_flow_category` (see section 3),
--    NOT the live maker-checker `category` column — see header note.
--
--    Depends on objects created in sections 3, 5, 6, 13 below — create this
--    function AFTER running those sections (it is placed here only to mirror
--    the requested numbering; reorder when actually running if you execute
--    section-by-section instead of the whole file at once).
-- =====================================================================

CREATE OR REPLACE FUNCTION get_branch_profit_loss(
  branch_id INTEGER,
  start_date DATE,
  end_date DATE
)
RETURNS JSONB AS $$
DECLARE
  v_system_revenue NUMERIC := 0;
  v_rev_mpesa NUMERIC := 0;
  v_rev_cash NUMERIC := 0;
  v_rev_card NUMERIC := 0;
  v_rev_credit NUMERIC := 0;
  v_verified_revenue NUMERIC := 0;
  v_exp_daily_purchase NUMERIC := 0;
  v_exp_petty_cash NUMERIC := 0;
  v_exp_transaction_cost NUMERIC := 0;
  v_exp_operational NUMERIC := 0;
  v_cogs NUMERIC := 0;
  v_gross_profit NUMERIC := 0;
  v_net_profit NUMERIC := 0;
  v_total_expenses NUMERIC := 0;
BEGIN
  -- Revenue by payment method: cashier_shifts joined with cashier_shift_transactions
  -- (normalizing legacy payment_method spellings defensively, e.g. 'credit_bill' -> 'credit')
  SELECT
    COALESCE(SUM(CASE WHEN norm.method = 'mpesa' THEN norm.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN norm.method = 'cash' THEN norm.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN norm.method = 'card' THEN norm.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN norm.method = 'credit' THEN norm.amount ELSE 0 END), 0)
  INTO v_rev_mpesa, v_rev_cash, v_rev_card, v_rev_credit
  FROM (
    SELECT
      cst.amount,
      CASE lower(cst.payment_method)
        WHEN 'credit_bill' THEN 'credit'
        WHEN 'mobile_money' THEN 'mpesa'
        ELSE lower(cst.payment_method)
      END AS method
    FROM cashier_shift_transactions cst
    JOIN cashier_shifts cs ON cs.id = cst.shift_id
    WHERE cs.branch_id = get_branch_profit_loss.branch_id
      AND cs.opened_at::date BETWEEN start_date AND end_date
  ) norm;

  v_system_revenue := v_rev_mpesa + v_rev_cash + v_rev_card + v_rev_credit;

  -- Accountant-verified revenue: shift_actual_collections (section 6)
  SELECT COALESCE(SUM(sac.actual_amount), 0)
  INTO v_verified_revenue
  FROM shift_actual_collections sac
  JOIN cashier_shifts cs ON cs.id = sac.shift_id
  WHERE sac.branch_id = get_branch_profit_loss.branch_id
    AND cs.opened_at::date BETWEEN start_date AND end_date;

  -- Outbound payments by category: branch_payments.cash_flow_category (section 3)
  -- — NOT the maker-checker `category` column, see header DEVIATION note.
  SELECT
    COALESCE(SUM(CASE WHEN bp.cash_flow_category = 'daily_purchase' THEN bp.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN bp.cash_flow_category = 'petty_cash' THEN bp.amount ELSE 0 END), 0),
    COALESCE(SUM(CASE WHEN bp.cash_flow_category = 'transaction_cost' THEN bp.amount ELSE 0 END), 0)
  INTO v_exp_daily_purchase, v_exp_petty_cash, v_exp_transaction_cost
  FROM branch_payments bp
  WHERE bp.branch_id = get_branch_profit_loss.branch_id
    AND bp.created_at::date BETWEEN start_date AND end_date;

  -- Shift-level reconciliation expenses (section 6) — additive to branch_payments,
  -- since these are cashier-recorded petty_cash/transaction_cost entries distinct
  -- from PO-driven branch_payments.
  SELECT
    v_exp_petty_cash + COALESCE(SUM(CASE WHEN sre.category = 'petty_cash' THEN sre.amount ELSE 0 END), 0),
    v_exp_transaction_cost + COALESCE(SUM(CASE WHEN sre.category = 'transaction_cost' THEN sre.amount ELSE 0 END), 0)
  INTO v_exp_petty_cash, v_exp_transaction_cost
  FROM shift_reconciliation_expenses sre
  JOIN cashier_shifts cs ON cs.id = sre.shift_id
  WHERE sre.branch_id = get_branch_profit_loss.branch_id
    AND cs.opened_at::date BETWEEN start_date AND end_date;

  -- Operational expenses: branch_stock_movements flagged is_operational_expense
  -- (section 13), restricted to out-movements via the same predicate
  -- stock_out_records (the view) uses internally.
  SELECT COALESCE(SUM(bsm.line_cost), 0)
  INTO v_exp_operational
  FROM branch_stock_movements bsm
  WHERE bsm.branch_id = get_branch_profit_loss.branch_id
    AND bsm.is_operational_expense = true
    AND bsm.created_at::date BETWEEN start_date AND end_date
    AND (
      bsm.quantity < 0
      OR lower(COALESCE(bsm.movement_type, '')) = ANY (ARRAY['stock_out','out','issue','department_issue','pos_issue','kitchen_issue','usage'])
    );

  -- COGS: received PO line costs from the real base tables (see header note —
  -- store_grn/store_grn_items are just views over these same two tables and
  -- must NOT also be summed, or every line gets counted twice).
  SELECT COALESCE(SUM(grl.line_total), 0)
  INTO v_cogs
  FROM goods_receipt_lines grl
  JOIN goods_receipts gr ON gr.id = grl.goods_receipt_id
  WHERE gr.branch_id = get_branch_profit_loss.branch_id
    AND gr.received_at::date BETWEEN start_date AND end_date;

  v_total_expenses := v_exp_daily_purchase + v_exp_petty_cash + v_exp_transaction_cost + v_exp_operational;
  v_gross_profit := v_system_revenue - v_cogs;
  v_net_profit := v_gross_profit - v_total_expenses;

  RETURN jsonb_build_object(
    'system_revenue', round(v_system_revenue, 2),
    'system_revenue_by_method', jsonb_build_object(
      'mpesa', round(v_rev_mpesa, 2),
      'cash', round(v_rev_cash, 2),
      'card', round(v_rev_card, 2),
      'credit', round(v_rev_credit, 2)
    ),
    'verified_revenue', round(v_verified_revenue, 2),
    'revenue_variance', round(v_verified_revenue - v_system_revenue, 2),
    'expenses_by_category', jsonb_build_object(
      'daily_purchase', round(v_exp_daily_purchase, 2),
      'petty_cash', round(v_exp_petty_cash, 2),
      'transaction_cost', round(v_exp_transaction_cost, 2),
      'operational', round(v_exp_operational, 2)
    ),
    'cogs', round(v_cogs, 2),
    'gross_profit', round(v_gross_profit, 2),
    'net_profit', round(v_net_profit, 2),
    'net_margin', CASE WHEN v_system_revenue = 0 THEN 0 ELSE round((v_net_profit / v_system_revenue) * 100, 2) END
  );
END;
$$ LANGUAGE plpgsql STABLE;


-- =====================================================================
-- 3. OUTBOUND PAYMENTS TABLE
--    DEVIATION: outbound_payments does not exist — the live table for this is
--    `branch_payments` (backend/migrations/20260611_branch_payments.sql), which
--    already runs a maker-checker approval workflow on its own `category` and
--    `status` columns. Reusing those columns and constraining them to the
--    request's vocabulary would reject every existing row outside
--    {daily_purchase,petty_cash,transaction_cost} / {pending,settled} — i.e. it
--    would break the live approval workflow. Adding new, non-colliding columns
--    instead: `cash_flow_category` / `settlement_status` carry the requested
--    P&L vocabulary, and `purchase_order_id` is a dedicated FK separate from
--    the existing generic `po_id` (which is shared three-way-match bookkeeping
--    for manually-created payments, not specifically "auto-generated by the
--    cash-PO trigger").
-- =====================================================================

ALTER TABLE branch_payments
ADD COLUMN IF NOT EXISTS cash_flow_category TEXT CHECK (cash_flow_category IN ('daily_purchase','petty_cash','transaction_cost')),
ADD COLUMN IF NOT EXISTS source TEXT CHECK (source IN ('purchase_order','manual_accountant')),
ADD COLUMN IF NOT EXISTS settlement_status TEXT DEFAULT 'pending' CHECK (settlement_status IN ('pending','settled')),
ADD COLUMN IF NOT EXISTS purchase_order_id UUID REFERENCES purchase_orders(id) ON DELETE SET NULL;


-- =====================================================================
-- 4. PURCHASE ORDER CASH FLAG AND TRIGGER
--    DEVIATION: purchase_orders.branch_id is a real, existing INTEGER column —
--    used directly (the earlier "receiving_branch_id" fix was itself wrong,
--    see header note).
--    DEVIATION: confirmed live values — payment_terms and status are both plain
--    TEXT (not enums, contrary to an earlier draft of this file — confirmed via
--    information_schema). 'cash' and 'received' are real values used by
--    backend/src/schemas/purchaseOrder.schema.ts (PaymentTermsEnum/POStatusEnum).
--    DEVIATION (bug fix): original spec declared this trigger AFTER INSERT while
--    mutating NEW.is_daily_expense inside the function — that assignment is a
--    no-op in an AFTER trigger. Changed to BEFORE INSERT so the flag persists.
--    DEVIATION: inserts into branch_payments (see section 3), which has NOT NULL
--    `payee_name` and `payment_method` columns the original spec's INSERT didn't
--    account for. purchase_orders has no supplier_name column, so payee_name is
--    resolved via a `suppliers` lookup on NEW.supplier_id (suppliers.name
--    confirmed to exist); payment_method is a literal 'cash'. The maker-checker
--    `status` column is left at its own default ('pending' in the
--    approval-workflow sense) — only the new `settlement_status` column is
--    managed by this trigger pair.
--    DEVIATION: uses NEW.created_by_id, not NEW.created_by — the app explicitly
--    writes created_by_id (backend/src/controllers/storekeeping/purchase-orders.controller.ts:470,
--    "Override created_by_id with the correct field name"); created_by exists
--    as a column but is not the one the app populates.
--    ADDITION (per follow-up request): branch_payments has a companion
--    append-only audit trail, `branch_payment_audit` (same migration file),
--    written by the app on every manual create/approve/release/reject via
--    backend/src/controllers/branch-payments.controller.ts's writeAudit()
--    helper (action='created'|'manager_approved'|'director_approved'|
--    'released'|'rejected'|'auto_released', plus actor_id/actor_name/actor_role/
--    ip_address from the HTTP request). A DB trigger has no HTTP request
--    context, so actor_id/ip_address are left NULL and actor_name/actor_role
--    are stamped as a literal "system" identity — but an audit row is still
--    written for both the auto-create and auto-settle events, action labelled
--    'created' and 'settled' respectively, so these trigger-generated payments
--    are not invisible in the existing audit trail UI
--    (backend/src/controllers/branch-payments.controller.ts:598 lists audit
--    rows by payment_id with no filter on actor, so trigger-authored rows
--    will show up there alongside human-authored ones).
-- =====================================================================

ALTER TABLE purchase_orders
ADD COLUMN IF NOT EXISTS is_daily_expense BOOLEAN DEFAULT false;

CREATE OR REPLACE FUNCTION fn_po_cash_create_outbound()
RETURNS TRIGGER AS $$
DECLARE
  v_payment_id UUID;
  v_payee_name TEXT;
BEGIN
  IF NEW.payment_terms = 'cash' THEN
    NEW.is_daily_expense := true;

    SELECT name INTO v_payee_name FROM suppliers WHERE id = NEW.supplier_id;
    v_payee_name := COALESCE(v_payee_name, 'Unknown supplier');

    INSERT INTO branch_payments (
      branch_id, purchase_order_id, amount, payee_name, payment_method,
      cash_flow_category, source, settlement_status, description, created_by, created_at
    ) VALUES (
      NEW.branch_id, NEW.id, NEW.total_amount,
      v_payee_name, 'cash',
      'daily_purchase', 'purchase_order', 'pending',
      'Auto-generated from cash purchase order ' || NEW.po_number, NEW.created_by_id, NOW()
    )
    RETURNING id INTO v_payment_id;

    INSERT INTO branch_payment_audit (payment_id, action, actor_id, actor_name, actor_role, details)
    VALUES (
      v_payment_id, 'created', NEW.created_by_id, 'System: PO cash-trigger', 'system',
      jsonb_build_object('source', 'purchase_order_trigger', 'purchase_order_id', NEW.id, 'po_number', NEW.po_number)
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_po_cash_outbound ON purchase_orders;
CREATE TRIGGER trg_po_cash_outbound
BEFORE INSERT ON purchase_orders
FOR EACH ROW EXECUTE FUNCTION fn_po_cash_create_outbound();

CREATE OR REPLACE FUNCTION fn_po_received_settle_outbound()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'received' AND OLD.status != 'received' THEN
    WITH updated AS (
      UPDATE branch_payments
      SET settlement_status = 'settled'
      WHERE purchase_order_id = NEW.id
        AND settlement_status != 'settled'
      RETURNING id
    )
    INSERT INTO branch_payment_audit (payment_id, action, actor_name, actor_role, details)
    SELECT id, 'settled', 'System: PO received-settle trigger', 'system',
           jsonb_build_object('purchase_order_id', NEW.id)
    FROM updated;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_po_received_settle ON purchase_orders;
CREATE TRIGGER trg_po_received_settle
AFTER UPDATE ON purchase_orders
FOR EACH ROW EXECUTE FUNCTION fn_po_received_settle_outbound();


-- =====================================================================
-- 5. PAYMENT METHOD COLUMNS
--    DEVIATION: cashier_shift_payments does not exist — applying this
--    normalization to the two live tables that actually carry payment_method:
--    pos_transactions (already has the column, varchar(20), no CHECK) and
--    cashier_shift_transactions (already has the column, text, no CHECK; this
--    is the table standing in for "cashier_shift_payments").
--
--    Run the diagnostic SELECTs first and eyeball the output before applying
--    the CHECK constraints — if any value outside {mpesa,cash,card,credit}
--    turns up beyond what's normalized below (e.g. 'bank_transfer','cheque'
--    seen in backend/migrations/20260108_kitchen_cashier_enhancements.sql),
--    the ADD CONSTRAINT statements will fail and that value needs a manual
--    decision on which bucket it belongs in before re-running.
-- =====================================================================

-- Diagnostic: inspect current distinct values before normalizing/constraining
SELECT payment_method, COUNT(*) FROM pos_transactions GROUP BY payment_method ORDER BY 1;
SELECT payment_method, COUNT(*) FROM cashier_shift_transactions GROUP BY payment_method ORDER BY 1;

-- Normalize known variants
UPDATE pos_transactions SET payment_method = lower(payment_method) WHERE payment_method <> lower(payment_method);
UPDATE pos_transactions SET payment_method = 'credit' WHERE payment_method IN ('credit_bill', 'mobile_money');

UPDATE cashier_shift_transactions SET payment_method = lower(payment_method) WHERE payment_method <> lower(payment_method);
UPDATE cashier_shift_transactions SET payment_method = 'credit' WHERE payment_method IN ('credit_bill', 'mobile_money');

-- pos_transactions.payment_method already exists (varchar(20), nullable) — add the
-- normalized CHECK constraint rather than re-adding the column.
ALTER TABLE pos_transactions
  DROP CONSTRAINT IF EXISTS pos_transactions_payment_method_check;
ALTER TABLE pos_transactions
  ADD CONSTRAINT pos_transactions_payment_method_check
  CHECK (payment_method IS NULL OR payment_method IN ('mpesa','cash','card','credit'));

-- cashier_shift_transactions.payment_method already exists (text, NOT NULL) — add
-- the normalized CHECK constraint (standing in for the requested
-- cashier_shift_payments.payment_method check).
ALTER TABLE cashier_shift_transactions
  DROP CONSTRAINT IF EXISTS cashier_shift_transactions_payment_method_check;
ALTER TABLE cashier_shift_transactions
  ADD CONSTRAINT cashier_shift_transactions_payment_method_check
  CHECK (payment_method IN ('mpesa','cash','card','credit'));


-- =====================================================================
-- 6. SHIFT RECONCILIATION TABLES
--    DEVIATION: branch_id corrected to INTEGER REFERENCES branches(id)
--    (branches.id is int4, not UUID).
-- =====================================================================

CREATE TABLE IF NOT EXISTS shift_actual_collections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES cashier_shifts(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  payment_method TEXT NOT NULL CHECK (payment_method IN ('mpesa','cash','card','credit')),
  system_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  actual_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  variance NUMERIC(12,2) GENERATED ALWAYS AS (actual_amount - system_amount) STORED,
  verified_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shift_reconciliation_expenses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES cashier_shifts(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  category TEXT NOT NULL CHECK (category IN ('petty_cash','transaction_cost','other')),
  amount NUMERIC(12,2) NOT NULL,
  description TEXT,
  recorded_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =====================================================================
-- 7. PAYMENTS DEDUPLICATION
--    DEVIATION: the live generic `payments` table is a hotel booking/folio
--    ledger (booking_id, folio_id) with no shift_id or pos_transaction_id
--    columns — it is not where cashier/POS duplicates occur. The table that
--    actually has shift_id + a transaction reference + payment_method + amount
--    is `cashier_shift_transactions` (transaction_id stands in for
--    pos_transaction_id). Retargeting this entire section to it.
--
--    DEVIATION: existing rows predate any source tagging, so "keep the
--    cashier-sourced record, delete the POS duplicate" can only be applied
--    going forward once `source` is populated by the app. For the one-time
--    cleanup of existing duplicates, the dedup below prefers a row tagged
--    source = 'cashier' over 'pos' when both exist for the same
--    (shift_id, transaction_id, payment_method, amount) tuple, and otherwise
--    falls back to keeping the lowest id (oldest row) since provenance is
--    unknown for legacy data.
-- =====================================================================

-- Diagnostic: show duplicate payment rows before touching anything
SELECT shift_id, transaction_id, payment_method, amount, COUNT(*)
FROM cashier_shift_transactions
GROUP BY shift_id, transaction_id, payment_method, amount
HAVING COUNT(*) > 1;

ALTER TABLE cashier_shift_transactions
ADD COLUMN IF NOT EXISTS source TEXT CHECK (source IN ('cashier','pos'));

-- Run this DELETE before adding the unique constraint below.
WITH ranked AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY shift_id, transaction_id, payment_method, amount
      ORDER BY
        CASE source WHEN 'cashier' THEN 0 WHEN 'pos' THEN 1 ELSE 2 END,
        id
    ) AS rn
  FROM cashier_shift_transactions
)
DELETE FROM cashier_shift_transactions cst
USING ranked
WHERE cst.id = ranked.id
  AND ranked.rn > 1;

ALTER TABLE cashier_shift_transactions
ADD CONSTRAINT uq_cst_shift_txn_method_amount
  UNIQUE (shift_id, transaction_id, payment_method, amount);


-- =====================================================================
-- 8. VOID ITEMS COLUMN
--    DEVIATION: the bill line items table is restaurant_order_items
--    (order_id, menu_item_id, quantity, unit_price, total_price), joined to
--    restaurant_menu_items for the item name (restaurant_order_items has no
--    item_name column of its own). void_requests.order_id is the join key.
-- =====================================================================

ALTER TABLE void_requests
ADD COLUMN IF NOT EXISTS void_items JSONB DEFAULT '[]'::jsonb;

COMMENT ON COLUMN void_requests.void_items IS
'Array of {item_id, item_name, quantity, unit_price, line_total} populated at void request creation time';

-- Backfill: best-effort reconstruction for existing void_requests from the
-- order's line items at the time of backfill (not necessarily the exact lines
-- that were voided, since void_requests does not currently record which
-- specific lines were voided — this is the closest available reconstruction).
UPDATE void_requests vr
SET void_items = backfill.items
FROM (
  SELECT
    roi.order_id,
    jsonb_agg(
      jsonb_build_object(
        'item_id', roi.menu_item_id,
        'item_name', rmi.name,
        'quantity', roi.quantity,
        'unit_price', roi.unit_price,
        'line_total', roi.total_price
      )
    ) AS items
  FROM restaurant_order_items roi
  LEFT JOIN restaurant_menu_items rmi ON rmi.id = roi.menu_item_id
  GROUP BY roi.order_id
) backfill
WHERE vr.order_id = backfill.order_id
  AND (vr.void_items IS NULL OR vr.void_items = '[]'::jsonb);


-- =====================================================================
-- 9. OPENING STOCK GATE TABLES
--    DEVIATION: branch_id corrected to INTEGER REFERENCES branches(id);
--    item_id corrected to UUID REFERENCES inventory_items(id) — confirmed live
--    via information_schema (the snapshot file claimed INTEGER and was wrong,
--    see header note).
-- =====================================================================

CREATE TABLE IF NOT EXISTS shift_opening_stock (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES cashier_shifts(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  stock_location TEXT NOT NULL CHECK (stock_location IN ('branch_store','main_bar','executive_bar')),
  item_id UUID NOT NULL REFERENCES inventory_items(id),
  system_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
  actual_quantity NUMERIC(12,3) NOT NULL DEFAULT 0,
  variance NUMERIC(12,3) GENERATED ALWAYS AS (actual_quantity - system_quantity) STORED,
  submitted_by UUID REFERENCES users(id),
  submitted_at TIMESTAMPTZ,
  UNIQUE(shift_id, stock_location, item_id)
);

CREATE TABLE IF NOT EXISTS shift_opening_stock_status (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  shift_id UUID NOT NULL REFERENCES cashier_shifts(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  branch_store_complete BOOLEAN DEFAULT false,
  main_bar_complete BOOLEAN DEFAULT false,
  executive_bar_complete BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  UNIQUE(shift_id)
);

CREATE OR REPLACE FUNCTION check_opening_stock_complete(p_shift_id UUID)
RETURNS BOOLEAN AS $$
DECLARE
  v_status shift_opening_stock_status%ROWTYPE;
BEGIN
  SELECT * INTO v_status FROM shift_opening_stock_status WHERE shift_id = p_shift_id;
  IF NOT FOUND THEN RETURN FALSE; END IF;
  -- Only Kyogong (branch 1) has a separate Executive Bar outlet — every other
  -- branch has just one bar, so executive_bar_complete must not be required there.
  RETURN v_status.branch_store_complete
     AND v_status.main_bar_complete
     AND (v_status.branch_id != 1 OR v_status.executive_bar_complete);
END;
$$ LANGUAGE plpgsql;


-- =====================================================================
-- 10. STOCK BALANCE LEDGER
--     DEVIATION: branch_id corrected to INTEGER; item_id corrected to UUID
--     REFERENCES inventory_items(id) — confirmed live (see header note).
--     DEVIATION: grn_items/goods_received_notes do not exist. The real
--     receiving-line table is goods_receipt_lines (FK column goods_receipt_id
--     -> goods_receipts.id), which already carries item_id (UUID) and
--     quantity_received directly; goods_receipts already has its own
--     branch_id (INTEGER) — no join through purchase_orders is needed at all,
--     unlike the original grn_items-based draft.
--     DEVIATION: an earlier pass of this file also attached a second copy of
--     this trigger to `store_grn_items`, believing it was a separate receiving
--     flow. It is not — store_grn_items is a plain view over goods_receipt_lines
--     (confirmed via pg_views), and Postgres does not allow row-level triggers
--     on views at all (`ERROR 42809: "store_grn_items" is a view`). Removed;
--     the single trigger on goods_receipt_lines below already fires for inserts
--     made through the store_grn_items view too, since it's a simple,
--     unfiltered, single-table view and Postgres forwards inserts through such
--     views to the underlying base table automatically.
--     DEVIATION: "stock_out_lines" = branch_stock_movements (the real table
--     behind the stock_out_records view — see header note), which stores
--     BOTH stock-in and stock-out rows with a SIGNED quantity (negative for
--     outs), and already has item_id UUID directly. fn_update_ledger_on_issue
--     attaches to branch_stock_movements (not the view — views can't have row
--     triggers) and guards on the same "is this an out-movement" predicate
--     the view uses, using abs(quantity) as the issued amount and falling
--     back to an item_code lookup only if item_id is ever null.
-- =====================================================================

CREATE TABLE IF NOT EXISTS stock_balance_ledger (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  item_id UUID NOT NULL REFERENCES inventory_items(id),
  ledger_date DATE NOT NULL DEFAULT CURRENT_DATE,
  opening_balance NUMERIC(12,3) NOT NULL DEFAULT 0,
  additional_stock NUMERIC(12,3) NOT NULL DEFAULT 0,
  issued_stock NUMERIC(12,3) NOT NULL DEFAULT 0,
  closing_balance NUMERIC(12,3) GENERATED ALWAYS AS (opening_balance + additional_stock - issued_stock) STORED,
  actual_closing NUMERIC(12,3),
  variance NUMERIC(12,3),
  UNIQUE(branch_id, item_id, ledger_date)
);

CREATE OR REPLACE FUNCTION fn_update_ledger_on_receive_goods_receipt()
RETURNS TRIGGER AS $$
DECLARE
  v_branch_id INTEGER;
BEGIN
  SELECT branch_id INTO v_branch_id FROM goods_receipts WHERE id = NEW.goods_receipt_id;
  IF v_branch_id IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO stock_balance_ledger (branch_id, item_id, ledger_date, additional_stock)
  VALUES (v_branch_id, NEW.item_id, CURRENT_DATE, NEW.quantity_received)
  ON CONFLICT (branch_id, item_id, ledger_date)
  DO UPDATE SET additional_stock = stock_balance_ledger.additional_stock + EXCLUDED.additional_stock;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_goods_receipt_lines_update_ledger ON goods_receipt_lines;
CREATE TRIGGER trg_goods_receipt_lines_update_ledger
AFTER INSERT ON goods_receipt_lines
FOR EACH ROW EXECUTE FUNCTION fn_update_ledger_on_receive_goods_receipt();

CREATE OR REPLACE FUNCTION fn_update_ledger_on_issue()
RETURNS TRIGGER AS $$
DECLARE
  v_item_id UUID;
  v_is_out_movement BOOLEAN;
BEGIN
  v_is_out_movement := (
    NEW.quantity < 0
    OR lower(COALESCE(NEW.movement_type, '')) = ANY (ARRAY['stock_out','out','issue','department_issue','pos_issue','kitchen_issue','usage'])
  );
  IF NOT v_is_out_movement THEN
    RETURN NEW;
  END IF;

  v_item_id := NEW.item_id;
  IF v_item_id IS NULL THEN
    SELECT id INTO v_item_id FROM inventory_items WHERE item_code = NEW.item_sku;
  END IF;
  IF v_item_id IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO stock_balance_ledger (branch_id, item_id, ledger_date, issued_stock)
  VALUES (NEW.branch_id, v_item_id, CURRENT_DATE, abs(NEW.quantity))
  ON CONFLICT (branch_id, item_id, ledger_date)
  DO UPDATE SET issued_stock = stock_balance_ledger.issued_stock + EXCLUDED.issued_stock;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_branch_stock_movements_update_ledger ON branch_stock_movements;
CREATE TRIGGER trg_branch_stock_movements_update_ledger
AFTER INSERT ON branch_stock_movements
FOR EACH ROW EXECUTE FUNCTION fn_update_ledger_on_issue();


-- =====================================================================
-- 11. KITCHEN LEDGER CONFIGURABLE ITEMS
--     DEVIATION: branch_id corrected to INTEGER; item_id corrected to UUID
--     REFERENCES inventory_items(id) — confirmed live (see header note).
--     NOTE: a different, similarly-named table `kitchen_ledger_entries`
--     already exists (backend/migrations/20260108_kitchen_cashier_enhancements.sql)
--     — that table records actual kitchen ledger transactions, this new one
--     is the per-branch enable/disable toggle list. They are not the same
--     thing and this migration does not touch kitchen_ledger_entries.
-- =====================================================================

CREATE TABLE IF NOT EXISTS kitchen_ledger_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  item_id UUID NOT NULL REFERENCES inventory_items(id),
  enabled_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(branch_id, item_id)
);


-- =====================================================================
-- 12. PASTRY PRODUCTION LOG
--     DEVIATION: branch_id corrected to INTEGER; item_id corrected to UUID
--     REFERENCES inventory_items(id) — confirmed live (see header note).
--     shift_id UUID REFERENCES cashier_shifts(id) required no correction.
-- =====================================================================

CREATE TABLE IF NOT EXISTS pastry_production_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  shift_id UUID REFERENCES cashier_shifts(id),
  item_id UUID NOT NULL REFERENCES inventory_items(id),
  quantity_produced NUMERIC(12,3) NOT NULL,
  issued_to_kitchen BOOLEAN DEFAULT false,
  issued_quantity NUMERIC(12,3),
  issued_at TIMESTAMPTZ,
  produced_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- =====================================================================
-- 13. NON-SALE STOCK OUT TRACKING
--     DEVIATION: stock_out_lines does not exist — and the closest live name,
--     stock_out_records, is a VIEW (see header note), so the new columns and
--     trigger below target the real base table, branch_stock_movements,
--     which already has item_id UUID directly (item_code/item_sku lookup is
--     only a fallback). The trigger guards on the same "is this an
--     out-movement" predicate the view uses, since branch_stock_movements
--     also stores stock-IN rows that must not be flagged.
--     DEVIATION: inventory_items has no is_for_sale column — adding it here.
--     Defaulting to TRUE so existing sellable catalogue items are not
--     retroactively misflagged as operational expenses; items that are
--     genuinely non-sale (cleaning supplies, internal-use stock, etc.) need a
--     manual UPDATE to set is_for_sale = false after this migration runs.
-- =====================================================================

ALTER TABLE inventory_items
ADD COLUMN IF NOT EXISTS is_for_sale BOOLEAN DEFAULT true;

ALTER TABLE branch_stock_movements
ADD COLUMN IF NOT EXISTS is_operational_expense BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS line_cost NUMERIC(12,2);

CREATE OR REPLACE FUNCTION fn_flag_operational_expense()
RETURNS TRIGGER AS $$
DECLARE
  v_is_out_movement BOOLEAN;
BEGIN
  v_is_out_movement := (
    NEW.quantity < 0
    OR lower(COALESCE(NEW.movement_type, '')) = ANY (ARRAY['stock_out','out','issue','department_issue','pos_issue','kitchen_issue','usage'])
  );
  IF NOT v_is_out_movement THEN
    RETURN NEW;
  END IF;

  IF EXISTS (
    SELECT 1 FROM inventory_items
    WHERE (id = NEW.item_id OR item_code = NEW.item_sku) AND is_for_sale = false
  ) THEN
    NEW.is_operational_expense := true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_flag_operational_expense ON branch_stock_movements;
CREATE TRIGGER trg_flag_operational_expense
BEFORE INSERT ON branch_stock_movements
FOR EACH ROW EXECUTE FUNCTION fn_flag_operational_expense();

-- =====================================================================
-- END OF MIGRATION
-- =====================================================================
