-- FamousGate Hotels clean database core schema
-- Target: brand-new Supabase/PostgreSQL project only.
-- Do not run this against the existing dirty production database.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS legacy_import;

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.current_branch_id()
RETURNS integer AS $$
  SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb->>'branch_id', '')::integer;
$$ LANGUAGE sql STABLE;

CREATE OR REPLACE FUNCTION public.current_user_uuid()
RETURNS uuid AS $$
  SELECT NULLIF(current_setting('request.jwt.claims', true)::jsonb->>'sub', '')::uuid;
$$ LANGUAGE sql STABLE;

-- ---------------------------------------------------------------------------
-- Identity and organization
-- ---------------------------------------------------------------------------

CREATE TABLE public.branches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  location text NOT NULL,
  legal_name text,
  email text,
  phone text,
  address text,
  city text,
  country text DEFAULT 'Kenya',
  manager_id uuid,
  is_main_branch boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'under_maintenance', 'under_renovation', 'coming_soon', 'closed')),
  is_central_warehouse boolean NOT NULL DEFAULT false,
  can_create_items boolean NOT NULL DEFAULT false,
  can_dispatch boolean NOT NULL DEFAULT false,
  warehouse_capacity integer NOT NULL DEFAULT 0,
  contact_person text,
  branch_type text NOT NULL DEFAULT 'hotel',
  number_of_rooms integer NOT NULL DEFAULT 0,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  timezone text NOT NULL DEFAULT 'Africa/Nairobi',
  currency text NOT NULL DEFAULT 'KES',
  logo_url text,
  opening_date date,
  default_till_number text,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  scope text NOT NULL CHECK (scope IN ('global', 'branch', 'outlet')),
  permissions jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid UNIQUE,
  email text NOT NULL UNIQUE,
  password_hash text,
  first_name text,
  last_name text,
  display_name text GENERATED ALWAYS AS (trim(coalesce(first_name, '') || ' ' || coalesce(last_name, ''))) STORED,
  phone text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'archived')),
  default_branch_id integer REFERENCES public.branches(id),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.user_branch_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  branch_id integer REFERENCES public.branches(id) ON DELETE CASCADE,
  role_id uuid NOT NULL REFERENCES public.roles(id),
  is_primary boolean NOT NULL DEFAULT false,
  valid_from timestamptz NOT NULL DEFAULT NOW(),
  valid_to timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, branch_id, role_id)
);

CREATE TABLE public.departments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  code text NOT NULL,
  name text NOT NULL,
  department_type text NOT NULL DEFAULT 'general',
  is_stock_destination boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, code)
);

CREATE TABLE public.staff_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  branch_id integer NOT NULL REFERENCES public.branches(id),
  department_id uuid REFERENCES public.departments(id),
  employee_number text,
  first_name text NOT NULL,
  last_name text,
  national_id text,
  phone text,
  email text,
  job_title text,
  employment_status text NOT NULL DEFAULT 'active' CHECK (employment_status IN ('active', 'inactive', 'terminated', 'on_leave')),
  hire_date date,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, employee_number)
);

-- ---------------------------------------------------------------------------
-- Audit, workflow, notifications, documents
-- ---------------------------------------------------------------------------

CREATE TABLE public.audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  actor_id uuid REFERENCES public.users(id),
  module text NOT NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  document_type text,
  document_id uuid,
  document_number text,
  old_data jsonb,
  new_data jsonb,
  reason text,
  ip_address inet,
  device_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.workflow_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  module text NOT NULL,
  task_type text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  assigned_role text,
  assigned_user_id uuid REFERENCES public.users(id),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_review', 'approved', 'rejected', 'returned', 'closed', 'cancelled')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  due_at timestamptz,
  notes text,
  created_by uuid REFERENCES public.users(id),
  decided_by uuid REFERENCES public.users(id),
  decided_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.documents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  document_type text NOT NULL,
  document_number text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'generated' CHECK (status IN ('generated', 'printed', 'downloaded', 'archived', 'voided')),
  storage_url text,
  checksum text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  generated_by uuid REFERENCES public.users(id),
  generated_at timestamptz NOT NULL DEFAULT NOW(),
  archived_at timestamptz,
  UNIQUE (document_type, document_number)
);

CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  recipient_user_id uuid REFERENCES public.users(id) ON DELETE CASCADE,
  recipient_role text,
  module text NOT NULL,
  title text NOT NULL,
  body text,
  severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'warning', 'critical')),
  status text NOT NULL DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'archived')),
  entity_type text,
  entity_id uuid,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  read_at timestamptz
);

-- ---------------------------------------------------------------------------
-- Hotel and reception
-- ---------------------------------------------------------------------------

CREATE TABLE public.guests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  first_name text NOT NULL,
  last_name text,
  phone text,
  email text,
  id_number text NOT NULL,
  id_type text NOT NULL DEFAULT 'national_id',
  car_plate text,
  loyalty_tier text DEFAULT 'bronze',
  loyalty_points numeric(14,2) NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.room_types (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  code text NOT NULL,
  name text NOT NULL,
  base_rate numeric(14,2) NOT NULL DEFAULT 0,
  max_occupancy integer NOT NULL DEFAULT 1,
  amenities jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, code)
);

CREATE TABLE public.rooms (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  room_type_id uuid REFERENCES public.room_types(id),
  room_number text NOT NULL,
  floor text,
  building text,
  status text NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'reserved', 'cleaning', 'maintenance', 'out_of_order')),
  housekeeping_status text NOT NULL DEFAULT 'clean' CHECK (housekeeping_status IN ('clean', 'dirty', 'being_cleaned', 'inspected')),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, room_number)
);

CREATE TABLE public.bookings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  booking_number text NOT NULL UNIQUE,
  guest_id uuid NOT NULL REFERENCES public.guests(id),
  room_id uuid REFERENCES public.rooms(id),
  booking_type text NOT NULL DEFAULT 'room' CHECK (booking_type IN ('room', 'conference', 'outside_catering')),
  status text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('draft', 'pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show')),
  check_in_at timestamptz,
  check_out_at timestamptz,
  pax integer NOT NULL DEFAULT 1,
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  service_charge numeric(14,2) NOT NULL DEFAULT 0,
  discount_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  amount_paid numeric(14,2) NOT NULL DEFAULT 0,
  payment_status text NOT NULL DEFAULT 'pending' CHECK (payment_status IN ('pending', 'partial', 'paid', 'refunded')),
  created_by uuid REFERENCES public.users(id),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  booking_id uuid REFERENCES public.bookings(id) ON DELETE CASCADE,
  reservation_number text NOT NULL UNIQUE,
  guest_id uuid NOT NULL REFERENCES public.guests(id),
  room_id uuid REFERENCES public.rooms(id),
  status text NOT NULL DEFAULT 'confirmed' CHECK (status IN ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show')),
  reserved_from timestamptz NOT NULL,
  reserved_to timestamptz NOT NULL,
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.folios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  folio_number text NOT NULL UNIQUE,
  booking_id uuid REFERENCES public.bookings(id),
  guest_id uuid REFERENCES public.guests(id),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed', 'voided')),
  total_charges numeric(14,2) NOT NULL DEFAULT 0,
  total_payments numeric(14,2) NOT NULL DEFAULT 0,
  balance_due numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.housekeeping_tasks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  room_id uuid REFERENCES public.rooms(id),
  task_number text NOT NULL UNIQUE,
  task_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  assigned_to uuid REFERENCES public.staff_profiles(id),
  requested_by uuid REFERENCES public.users(id),
  completed_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Inventory truth
-- ---------------------------------------------------------------------------

CREATE TABLE public.inventory_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku text NOT NULL UNIQUE,
  item_name text NOT NULL,
  description text,
  category text,
  unit text NOT NULL,
  item_type text NOT NULL DEFAULT 'stockable' CHECK (item_type IN ('stockable', 'service', 'menu_item', 'asset')),
  is_perishable boolean NOT NULL DEFAULT false,
  tracking_mode text NOT NULL DEFAULT 'standard' CHECK (tracking_mode IN ('standard', 'batch', 'lot', 'serial')),
  default_unit_cost numeric(14,4) NOT NULL DEFAULT 0,
  default_selling_price numeric(14,2) NOT NULL DEFAULT 0,
  reorder_level numeric(14,3) NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.inventory_locations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  location_code text NOT NULL,
  name text NOT NULL,
  location_type text NOT NULL CHECK (location_type IN ('central_store', 'branch_store', 'department', 'pos_outlet', 'production', 'supplier', 'waste', 'in_transit')),
  parent_location_id uuid REFERENCES public.inventory_locations(id),
  department_id uuid REFERENCES public.departments(id),
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, location_code)
);

CREATE TABLE public.inventory_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  batch_number text NOT NULL,
  lot_number text,
  supplier_id uuid,
  expiry_date date,
  manufacture_date date,
  unit_cost numeric(14,4) NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (item_id, batch_number)
);

CREATE TABLE public.inventory_balances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  location_id uuid NOT NULL REFERENCES public.inventory_locations(id),
  batch_id uuid REFERENCES public.inventory_batches(id),
  current_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (current_quantity >= 0),
  reserved_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  damaged_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (damaged_quantity >= 0),
  expired_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (expired_quantity >= 0),
  available_quantity numeric(14,3) GENERATED ALWAYS AS (current_quantity - reserved_quantity - damaged_quantity - expired_quantity) STORED,
  unit_cost numeric(14,4) NOT NULL DEFAULT 0,
  last_movement_id uuid,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CHECK (reserved_quantity + damaged_quantity + expired_quantity <= current_quantity),
  UNIQUE (item_id, location_id, batch_id)
);

CREATE TABLE public.inventory_movements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  movement_number text NOT NULL UNIQUE,
  branch_id integer REFERENCES public.branches(id),
  movement_type text NOT NULL CHECK (movement_type IN (
    'purchase_receipt', 'grn_posting', 'branch_requisition_dispatch',
    'central_store_packing', 'department_issue', 'pos_issue',
    'production_consumption', 'production_output', 'stock_take_adjustment',
    'return', 'write_off', 'transfer', 'reservation', 'reservation_release',
    'sale_consumption', 'wastage'
  )),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  batch_id uuid REFERENCES public.inventory_batches(id),
  source_location_id uuid REFERENCES public.inventory_locations(id),
  destination_location_id uuid REFERENCES public.inventory_locations(id),
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_cost numeric(14,4) NOT NULL DEFAULT 0,
  reason text NOT NULL,
  document_type text NOT NULL,
  document_id uuid,
  document_number text NOT NULL,
  actor_id uuid REFERENCES public.users(id),
  reversible boolean NOT NULL DEFAULT true,
  reversed_by_movement_id uuid REFERENCES public.inventory_movements(id),
  before_balance jsonb,
  after_balance jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  CHECK (source_location_id IS NOT NULL OR destination_location_id IS NOT NULL)
);

ALTER TABLE public.inventory_balances
  ADD CONSTRAINT inventory_balances_last_movement_fk
  FOREIGN KEY (last_movement_id) REFERENCES public.inventory_movements(id);

CREATE TABLE public.inventory_reservations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reservation_number text NOT NULL UNIQUE,
  branch_id integer REFERENCES public.branches(id),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  location_id uuid NOT NULL REFERENCES public.inventory_locations(id),
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  fulfilled_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (fulfilled_quantity >= 0),
  status text NOT NULL DEFAULT 'reserved' CHECK (status IN ('reserved', 'released', 'fulfilled', 'expired', 'cancelled')),
  source_document_type text NOT NULL,
  source_document_id uuid NOT NULL,
  source_document_number text NOT NULL,
  reserved_by uuid REFERENCES public.users(id),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CHECK (fulfilled_quantity <= quantity)
);

CREATE TABLE public.inventory_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  item_id uuid REFERENCES public.inventory_items(id),
  location_id uuid REFERENCES public.inventory_locations(id),
  alert_type text NOT NULL CHECK (alert_type IN ('low_stock', 'out_of_stock', 'expired_stock', 'damaged_stock', 'suspicious_movement', 'negative_balance_attempt', 'over_reservation_attempt')),
  severity text NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'critical')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed')),
  message text NOT NULL,
  source_document_type text,
  source_document_id uuid,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  resolved_at timestamptz
);

-- ---------------------------------------------------------------------------
-- POS, menu, outlet stock, production
-- ---------------------------------------------------------------------------

CREATE TABLE public.pos_outlets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  outlet_code text NOT NULL,
  name text NOT NULL,
  outlet_type text NOT NULL CHECK (outlet_type IN ('restaurant', 'main_bar', 'executive_bar', 'sports_bar', 'cashier', 'spa', 'kitchen', 'other')),
  inventory_location_id uuid REFERENCES public.inventory_locations(id),
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, outlet_code)
);

CREATE TABLE public.menu_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sku text UNIQUE,
  name text NOT NULL,
  category text,
  unit text NOT NULL DEFAULT 'unit',
  selling_price numeric(14,2) NOT NULL DEFAULT 0,
  cost_price numeric(14,4) NOT NULL DEFAULT 0,
  is_stock_tracked boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pos_outlet_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  outlet_id uuid NOT NULL REFERENCES public.pos_outlets(id) ON DELETE CASCADE,
  menu_item_id uuid NOT NULL REFERENCES public.menu_items(id),
  current_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
  reserved_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (reserved_stock >= 0),
  low_stock_level numeric(14,3) NOT NULL DEFAULT 0,
  selling_price numeric(14,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'sold_out', 'inactive')),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (outlet_id, menu_item_id),
  CHECK (reserved_stock <= current_stock)
);

CREATE TABLE public.production_recipes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  output_menu_item_id uuid NOT NULL REFERENCES public.menu_items(id),
  branch_id integer REFERENCES public.branches(id),
  recipe_name text NOT NULL,
  output_quantity numeric(14,3) NOT NULL DEFAULT 1 CHECK (output_quantity > 0),
  output_unit text NOT NULL DEFAULT 'unit',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'inactive')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.production_recipe_inputs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id uuid NOT NULL REFERENCES public.production_recipes(id) ON DELETE CASCADE,
  input_item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  quantity_required numeric(14,4) NOT NULL CHECK (quantity_required > 0),
  unit text NOT NULL,
  waste_factor numeric(8,4) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.production_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  production_number text NOT NULL UNIQUE,
  outlet_id uuid NOT NULL REFERENCES public.pos_outlets(id),
  recipe_id uuid REFERENCES public.production_recipes(id),
  output_menu_item_id uuid NOT NULL REFERENCES public.menu_items(id),
  quantity_produced numeric(14,3) NOT NULL CHECK (quantity_produced > 0),
  production_stage text NOT NULL CHECK (production_stage IN ('food_production', 'bar_stock_production', 'prepped_stock', 'assembled_stock', 'outlet_ready_stock')),
  batch_reference text,
  status text NOT NULL DEFAULT 'posted' CHECK (status IN ('draft', 'posted', 'voided')),
  operator_id uuid REFERENCES public.users(id),
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.production_run_inputs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  production_run_id uuid NOT NULL REFERENCES public.production_runs(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  quantity_consumed numeric(14,3) NOT NULL CHECK (quantity_consumed > 0),
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.production_run_outputs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  production_run_id uuid NOT NULL REFERENCES public.production_runs(id) ON DELETE CASCADE,
  outlet_item_id uuid NOT NULL REFERENCES public.pos_outlet_items(id),
  quantity_added numeric(14,3) NOT NULL CHECK (quantity_added > 0),
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pos_shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  outlet_id uuid NOT NULL REFERENCES public.pos_outlets(id),
  shift_number text NOT NULL UNIQUE,
  opened_by uuid REFERENCES public.users(id),
  closed_by uuid REFERENCES public.users(id),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closing', 'closed', 'voided')),
  opened_at timestamptz NOT NULL DEFAULT NOW(),
  closed_at timestamptz,
  opening_float numeric(14,2) NOT NULL DEFAULT 0,
  closing_float numeric(14,2) NOT NULL DEFAULT 0,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE public.pos_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  outlet_id uuid NOT NULL REFERENCES public.pos_outlets(id),
  shift_id uuid REFERENCES public.pos_shifts(id),
  order_number text NOT NULL UNIQUE,
  customer_name text,
  order_type text NOT NULL DEFAULT 'dine_in' CHECK (order_type IN ('dine_in', 'takeaway', 'room_service', 'delivery')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'submitted', 'completed', 'voided', 'cancelled')),
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pos_order_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES public.pos_orders(id) ON DELETE CASCADE,
  outlet_item_id uuid REFERENCES public.pos_outlet_items(id),
  menu_item_id uuid NOT NULL REFERENCES public.menu_items(id),
  item_name text NOT NULL,
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit_price numeric(14,2) NOT NULL DEFAULT 0,
  line_total numeric(14,2) NOT NULL DEFAULT 0,
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.pos_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  order_id uuid REFERENCES public.pos_orders(id),
  shift_id uuid REFERENCES public.pos_shifts(id),
  payment_number text NOT NULL UNIQUE,
  method text NOT NULL CHECK (method IN ('cash', 'mpesa', 'card', 'bank', 'credit', 'split')),
  amount numeric(14,2) NOT NULL CHECK (amount >= 0),
  status text NOT NULL DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'failed', 'reversed')),
  reference text,
  received_by uuid REFERENCES public.users(id),
  received_at timestamptz NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Procurement, GRN, supplier finance
-- ---------------------------------------------------------------------------

CREATE TABLE public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  supplier_code text NOT NULL,
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  tax_pin text,
  address text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'blocked')),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (branch_id, supplier_code)
);

CREATE TABLE public.purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  po_number text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  source_module text NOT NULL DEFAULT 'branch_store',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'pending_approval', 'approved', 'sent_to_supplier', 'partially_received', 'fully_received', 'cancelled', 'closed')),
  finance_status text NOT NULL DEFAULT 'not_billed' CHECK (finance_status IN ('not_billed', 'pending_bill', 'billed', 'approved_for_payment', 'partially_paid', 'paid_closed')),
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_delivery_date date,
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  discount_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  created_by uuid REFERENCES public.users(id),
  approved_by uuid REFERENCES public.users(id),
  approved_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.purchase_order_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL REFERENCES public.purchase_orders(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  item_name text NOT NULL,
  sku text NOT NULL,
  quantity_ordered numeric(14,3) NOT NULL CHECK (quantity_ordered > 0),
  quantity_received numeric(14,3) NOT NULL DEFAULT 0 CHECK (quantity_received >= 0),
  quantity_pending numeric(14,3) NOT NULL DEFAULT 0 CHECK (quantity_pending >= 0),
  unit text NOT NULL,
  unit_price numeric(14,4) NOT NULL DEFAULT 0,
  line_total numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  CHECK (quantity_received <= quantity_ordered)
);

CREATE TABLE public.goods_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  grn_number text NOT NULL UNIQUE,
  purchase_order_id uuid NOT NULL REFERENCES public.purchase_orders(id),
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  delivery_note_number text,
  invoice_number text,
  status text NOT NULL DEFAULT 'posted' CHECK (status IN ('draft', 'posted', 'partially_accepted', 'rejected', 'voided')),
  received_by uuid REFERENCES public.users(id),
  received_at timestamptz NOT NULL DEFAULT NOW(),
  total_quantity numeric(14,3) NOT NULL DEFAULT 0,
  total_value numeric(14,2) NOT NULL DEFAULT 0,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.goods_receipt_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  goods_receipt_id uuid NOT NULL REFERENCES public.goods_receipts(id) ON DELETE CASCADE,
  purchase_order_line_id uuid REFERENCES public.purchase_order_lines(id),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  item_name text NOT NULL,
  sku text NOT NULL,
  quantity_ordered numeric(14,3) NOT NULL DEFAULT 0,
  quantity_received numeric(14,3) NOT NULL CHECK (quantity_received >= 0),
  quantity_accepted numeric(14,3) NOT NULL CHECK (quantity_accepted >= 0),
  quantity_rejected numeric(14,3) NOT NULL DEFAULT 0 CHECK (quantity_rejected >= 0),
  unit text NOT NULL,
  unit_price numeric(14,4) NOT NULL DEFAULT 0,
  line_total numeric(14,2) NOT NULL DEFAULT 0,
  quality_status text NOT NULL DEFAULT 'accepted' CHECK (quality_status IN ('accepted', 'damaged', 'expired', 'rejected')),
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.supplier_invoices (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  invoice_number text NOT NULL,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  purchase_order_id uuid REFERENCES public.purchase_orders(id),
  goods_receipt_id uuid REFERENCES public.goods_receipts(id),
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'matched', 'approved_for_payment', 'partially_paid', 'paid', 'voided')),
  subtotal numeric(14,2) NOT NULL DEFAULT 0,
  tax_amount numeric(14,2) NOT NULL DEFAULT 0,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  amount_paid numeric(14,2) NOT NULL DEFAULT 0,
  balance_due numeric(14,2) NOT NULL DEFAULT 0,
  created_by uuid REFERENCES public.users(id),
  approved_by uuid REFERENCES public.users(id),
  approved_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (supplier_id, invoice_number)
);

CREATE TABLE public.supplier_invoice_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_invoice_id uuid NOT NULL REFERENCES public.supplier_invoices(id) ON DELETE CASCADE,
  goods_receipt_line_id uuid REFERENCES public.goods_receipt_lines(id),
  item_id uuid REFERENCES public.inventory_items(id),
  description text NOT NULL,
  quantity numeric(14,3) NOT NULL CHECK (quantity > 0),
  unit text NOT NULL,
  unit_price numeric(14,4) NOT NULL DEFAULT 0,
  line_total numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.supplier_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  payment_number text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  payment_method text NOT NULL CHECK (payment_method IN ('cash', 'mpesa', 'card', 'bank', 'cheque')),
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'released', 'rejected', 'voided')),
  reference text,
  created_by uuid REFERENCES public.users(id),
  released_by uuid REFERENCES public.users(id),
  released_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.supplier_payment_allocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_payment_id uuid NOT NULL REFERENCES public.supplier_payments(id) ON DELETE CASCADE,
  supplier_invoice_id uuid NOT NULL REFERENCES public.supplier_invoices(id),
  amount_allocated numeric(14,2) NOT NULL CHECK (amount_allocated > 0),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  UNIQUE (supplier_payment_id, supplier_invoice_id)
);

CREATE TABLE public.supplier_ledger (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id),
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  entry_type text NOT NULL CHECK (entry_type IN ('po', 'grn', 'invoice', 'payment', 'credit_note', 'adjustment')),
  document_type text NOT NULL,
  document_id uuid,
  document_number text NOT NULL,
  debit numeric(14,2) NOT NULL DEFAULT 0,
  credit numeric(14,2) NOT NULL DEFAULT 0,
  running_balance numeric(14,2),
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Branch requisition, dispatch, receipt, department issue
-- ---------------------------------------------------------------------------

CREATE TABLE public.branch_requisitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  request_number text NOT NULL UNIQUE,
  requested_by uuid REFERENCES public.users(id),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted_to_auditor', 'auditor_approved', 'auditor_rejected', 'returned_for_correction', 'sent_to_central_store', 'packing', 'dispatched', 'in_transit', 'received', 'verified', 'closed', 'cancelled')),
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  reason text,
  requested_at timestamptz NOT NULL DEFAULT NOW(),
  auditor_id uuid REFERENCES public.users(id),
  auditor_decided_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.branch_requisition_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_requisition_id uuid NOT NULL REFERENCES public.branch_requisitions(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  requested_quantity numeric(14,3) NOT NULL CHECK (requested_quantity > 0),
  approved_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (approved_quantity >= 0),
  packed_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (packed_quantity >= 0),
  received_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  unit text NOT NULL,
  line_status text NOT NULL DEFAULT 'pending' CHECK (line_status IN ('pending', 'approved', 'partially_approved', 'rejected', 'packed', 'partially_packed', 'received', 'shorted')),
  reason text,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.packing_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_requisition_id uuid NOT NULL REFERENCES public.branch_requisitions(id),
  packing_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'packing' CHECK (status IN ('packing', 'packed', 'partially_packed', 'cancelled')),
  packed_by uuid REFERENCES public.users(id),
  packed_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.packing_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  packing_session_id uuid NOT NULL REFERENCES public.packing_sessions(id) ON DELETE CASCADE,
  branch_requisition_line_id uuid NOT NULL REFERENCES public.branch_requisition_lines(id),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  packed_quantity numeric(14,3) NOT NULL CHECK (packed_quantity >= 0),
  unavailable_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (unavailable_quantity >= 0),
  unit text NOT NULL,
  source_location_id uuid REFERENCES public.inventory_locations(id),
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.dispatches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_requisition_id uuid REFERENCES public.branch_requisitions(id),
  packing_session_id uuid REFERENCES public.packing_sessions(id),
  dispatch_number text NOT NULL UNIQUE,
  source_branch_id integer REFERENCES public.branches(id),
  destination_branch_id integer REFERENCES public.branches(id),
  status text NOT NULL DEFAULT 'dispatched' CHECK (status IN ('draft', 'dispatched', 'in_transit', 'received', 'verified', 'cancelled')),
  vehicle_info text,
  courier_info text,
  dispatched_by uuid REFERENCES public.users(id),
  dispatched_at timestamptz,
  received_by uuid REFERENCES public.users(id),
  received_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.dispatch_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dispatch_id uuid NOT NULL REFERENCES public.dispatches(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  packed_quantity numeric(14,3) NOT NULL CHECK (packed_quantity >= 0),
  received_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  damaged_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (damaged_quantity >= 0),
  missing_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (missing_quantity >= 0),
  unit text NOT NULL,
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.receipt_verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dispatch_id uuid NOT NULL REFERENCES public.dispatches(id),
  verification_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'matched' CHECK (status IN ('matched', 'partially_matched', 'damaged', 'missing', 'extra', 'rejected')),
  verified_by uuid REFERENCES public.users(id),
  verified_at timestamptz NOT NULL DEFAULT NOW(),
  discrepancies jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.department_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  request_number text NOT NULL UNIQUE,
  department_id uuid REFERENCES public.departments(id),
  outlet_id uuid REFERENCES public.pos_outlets(id),
  requestor_name text NOT NULL,
  purpose text,
  shift text,
  event_name text,
  pax integer,
  status text NOT NULL DEFAULT 'logged' CHECK (status IN ('logged', 'pending_audit', 'audited', 'approved', 'rejected', 'issued', 'partially_issued', 'closed')),
  logged_by uuid REFERENCES public.users(id),
  logged_at timestamptz NOT NULL DEFAULT NOW(),
  remarks text,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.department_request_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  department_request_id uuid NOT NULL REFERENCES public.department_requests(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  requested_quantity numeric(14,3) NOT NULL CHECK (requested_quantity > 0),
  issued_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (issued_quantity >= 0),
  pending_quantity numeric(14,3) NOT NULL DEFAULT 0 CHECK (pending_quantity >= 0),
  unit text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'issued', 'partially_issued', 'rejected', 'backordered')),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.material_issue_notes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  min_number text NOT NULL UNIQUE,
  department_request_id uuid REFERENCES public.department_requests(id),
  destination_department_id uuid REFERENCES public.departments(id),
  destination_outlet_id uuid REFERENCES public.pos_outlets(id),
  status text NOT NULL DEFAULT 'issued' CHECK (status IN ('draft', 'issued', 'partially_issued', 'voided')),
  issued_by uuid REFERENCES public.users(id),
  issued_at timestamptz NOT NULL DEFAULT NOW(),
  notes text,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.material_issue_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  material_issue_note_id uuid NOT NULL REFERENCES public.material_issue_notes(id) ON DELETE CASCADE,
  department_request_line_id uuid REFERENCES public.department_request_lines(id),
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  requested_quantity numeric(14,3) NOT NULL DEFAULT 0,
  issued_quantity numeric(14,3) NOT NULL CHECK (issued_quantity > 0),
  pending_quantity numeric(14,3) NOT NULL DEFAULT 0,
  unit text NOT NULL,
  movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Stock take, finance, cashier
-- ---------------------------------------------------------------------------

CREATE TABLE public.stock_takes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  stock_take_number text NOT NULL UNIQUE,
  location_id uuid REFERENCES public.inventory_locations(id),
  outlet_id uuid REFERENCES public.pos_outlets(id),
  stock_take_type text NOT NULL CHECK (stock_take_type IN ('full_count', 'cycle_count', 'spot_count', 'blind_count', 'investigation_count', 'outlet_count', 'trading_stock_sheet')),
  period_start date,
  period_end date,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'started', 'counting', 'submitted', 'accountant_review', 'auditor_review', 'approved', 'posted', 'closed', 'cancelled')),
  prepared_by uuid REFERENCES public.users(id),
  reviewed_by uuid REFERENCES public.users(id),
  audited_by uuid REFERENCES public.users(id),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.stock_take_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_take_id uuid NOT NULL REFERENCES public.stock_takes(id) ON DELETE CASCADE,
  item_id uuid NOT NULL REFERENCES public.inventory_items(id),
  opening_quantity numeric(14,3) NOT NULL DEFAULT 0,
  added_quantity numeric(14,3) NOT NULL DEFAULT 0,
  system_quantity numeric(14,3) NOT NULL DEFAULT 0,
  counted_quantity numeric(14,3),
  sold_quantity numeric(14,3) NOT NULL DEFAULT 0,
  cost_price numeric(14,4) NOT NULL DEFAULT 0,
  selling_price numeric(14,2) NOT NULL DEFAULT 0,
  revenue_amount numeric(14,2) NOT NULL DEFAULT 0,
  cogs_amount numeric(14,2) NOT NULL DEFAULT 0,
  variance_quantity numeric(14,3),
  variance_value numeric(14,2),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'counted', 'variance', 'approved', 'posted')),
  notes text,
  adjustment_movement_id uuid REFERENCES public.inventory_movements(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.stock_take_variances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_take_line_id uuid NOT NULL REFERENCES public.stock_take_lines(id) ON DELETE CASCADE,
  variance_class text NOT NULL CHECK (variance_class IN ('small', 'medium', 'large', 'critical')),
  explanation text,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'investigating', 'approved', 'rejected', 'posted')),
  reviewed_by uuid REFERENCES public.users(id),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.cashier_shifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  cashier_id uuid REFERENCES public.users(id),
  shift_number text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'submitted', 'approved', 'closed', 'voided')),
  opening_float numeric(14,2) NOT NULL DEFAULT 0,
  closing_float numeric(14,2) NOT NULL DEFAULT 0,
  opened_at timestamptz NOT NULL DEFAULT NOW(),
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.cashier_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  cashier_shift_id uuid REFERENCES public.cashier_shifts(id),
  transaction_number text NOT NULL UNIQUE,
  transaction_type text NOT NULL CHECK (transaction_type IN ('sale', 'payment', 'refund', 'float_in', 'float_out', 'adjustment')),
  payment_method text CHECK (payment_method IN ('cash', 'mpesa', 'card', 'bank', 'credit', 'split')),
  amount numeric(14,2) NOT NULL DEFAULT 0,
  source_module text,
  source_document_type text,
  source_document_id uuid,
  source_document_number text,
  status text NOT NULL DEFAULT 'posted' CHECK (status IN ('pending', 'posted', 'voided', 'reversed')),
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.branch_payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  payment_number text NOT NULL UNIQUE,
  category text NOT NULL CHECK (category IN ('vendor', 'staff', 'utility', 'refund', 'other')),
  payee_name text NOT NULL,
  payee_account text,
  payment_method text NOT NULL CHECK (payment_method IN ('cash', 'mpesa', 'card', 'bank', 'cheque')),
  amount numeric(14,2) NOT NULL CHECK (amount > 0),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'manager_approved', 'awaiting_director', 'director_approved', 'released', 'rejected', 'voided')),
  po_id uuid REFERENCES public.purchase_orders(id),
  grn_id uuid REFERENCES public.goods_receipts(id),
  invoice_id uuid REFERENCES public.supplier_invoices(id),
  created_by uuid REFERENCES public.users(id),
  released_by uuid REFERENCES public.users(id),
  released_at timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.credit_bills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer NOT NULL REFERENCES public.branches(id),
  bill_number text NOT NULL UNIQUE,
  customer_name text NOT NULL,
  customer_phone text,
  source_module text NOT NULL,
  source_document_id uuid,
  source_document_number text,
  total_amount numeric(14,2) NOT NULL DEFAULT 0,
  amount_paid numeric(14,2) NOT NULL DEFAULT 0,
  balance_due numeric(14,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'partially_paid', 'paid', 'written_off', 'voided')),
  created_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.bank_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  account_name text NOT NULL,
  bank_name text NOT NULL,
  account_number text NOT NULL,
  currency text NOT NULL DEFAULT 'KES',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'closed')),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE public.bank_reconciliations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  branch_id integer REFERENCES public.branches(id),
  bank_account_id uuid NOT NULL REFERENCES public.bank_accounts(id),
  reconciliation_number text NOT NULL UNIQUE,
  period_start date NOT NULL,
  period_end date NOT NULL,
  statement_balance numeric(14,2) NOT NULL DEFAULT 0,
  system_balance numeric(14,2) NOT NULL DEFAULT 0,
  variance numeric(14,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'approved', 'rejected', 'closed')),
  prepared_by uuid REFERENCES public.users(id),
  approved_by uuid REFERENCES public.users(id),
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_users_default_branch ON public.users(default_branch_id);
CREATE INDEX idx_staff_branch ON public.staff_profiles(branch_id);
CREATE INDEX idx_audit_events_entity ON public.audit_events(entity_type, entity_id);
CREATE INDEX idx_audit_events_branch_created ON public.audit_events(branch_id, created_at DESC);
CREATE INDEX idx_workflow_tasks_status ON public.workflow_tasks(status, assigned_role);
CREATE INDEX idx_documents_entity ON public.documents(entity_type, entity_id);
CREATE INDEX idx_bookings_branch_status ON public.bookings(branch_id, status);
CREATE INDEX idx_rooms_branch_status ON public.rooms(branch_id, status);
CREATE INDEX idx_inventory_items_sku ON public.inventory_items(sku);
CREATE INDEX idx_inventory_locations_branch_type ON public.inventory_locations(branch_id, location_type);
CREATE INDEX idx_inventory_balances_location ON public.inventory_balances(location_id);
CREATE INDEX idx_inventory_movements_item_created ON public.inventory_movements(item_id, created_at DESC);
CREATE INDEX idx_inventory_movements_document ON public.inventory_movements(document_type, document_id);
CREATE INDEX idx_inventory_reservations_status ON public.inventory_reservations(status, source_document_type);
CREATE INDEX idx_pos_outlets_branch ON public.pos_outlets(branch_id);
CREATE INDEX idx_pos_orders_shift ON public.pos_orders(shift_id, status);
CREATE INDEX idx_purchase_orders_branch_status ON public.purchase_orders(branch_id, status);
CREATE INDEX idx_goods_receipts_po ON public.goods_receipts(purchase_order_id);
CREATE INDEX idx_supplier_invoices_status ON public.supplier_invoices(branch_id, status);
CREATE INDEX idx_supplier_payments_status ON public.supplier_payments(branch_id, status);
CREATE INDEX idx_branch_requisitions_status ON public.branch_requisitions(branch_id, status);
CREATE INDEX idx_dispatches_status ON public.dispatches(destination_branch_id, status);
CREATE INDEX idx_department_requests_status ON public.department_requests(branch_id, status);
CREATE INDEX idx_stock_takes_status ON public.stock_takes(branch_id, status);
CREATE INDEX idx_cashier_transactions_source ON public.cashier_transactions(source_module, source_document_id);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------

CREATE TRIGGER trg_branches_updated_at BEFORE UPDATE ON public.branches FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON public.roles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON public.departments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_staff_profiles_updated_at BEFORE UPDATE ON public.staff_profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_workflow_tasks_updated_at BEFORE UPDATE ON public.workflow_tasks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_guests_updated_at BEFORE UPDATE ON public.guests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_room_types_updated_at BEFORE UPDATE ON public.room_types FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_rooms_updated_at BEFORE UPDATE ON public.rooms FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_bookings_updated_at BEFORE UPDATE ON public.bookings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_reservations_updated_at BEFORE UPDATE ON public.reservations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_folios_updated_at BEFORE UPDATE ON public.folios FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_housekeeping_tasks_updated_at BEFORE UPDATE ON public.housekeeping_tasks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_inventory_items_updated_at BEFORE UPDATE ON public.inventory_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_inventory_locations_updated_at BEFORE UPDATE ON public.inventory_locations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_inventory_balances_updated_at BEFORE UPDATE ON public.inventory_balances FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_inventory_reservations_updated_at BEFORE UPDATE ON public.inventory_reservations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_pos_outlets_updated_at BEFORE UPDATE ON public.pos_outlets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_menu_items_updated_at BEFORE UPDATE ON public.menu_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_pos_outlet_items_updated_at BEFORE UPDATE ON public.pos_outlet_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_production_recipes_updated_at BEFORE UPDATE ON public.production_recipes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_production_runs_updated_at BEFORE UPDATE ON public.production_runs FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_pos_orders_updated_at BEFORE UPDATE ON public.pos_orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_suppliers_updated_at BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_purchase_orders_updated_at BEFORE UPDATE ON public.purchase_orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_purchase_order_lines_updated_at BEFORE UPDATE ON public.purchase_order_lines FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_goods_receipts_updated_at BEFORE UPDATE ON public.goods_receipts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_supplier_invoices_updated_at BEFORE UPDATE ON public.supplier_invoices FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_supplier_payments_updated_at BEFORE UPDATE ON public.supplier_payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_branch_requisitions_updated_at BEFORE UPDATE ON public.branch_requisitions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_packing_sessions_updated_at BEFORE UPDATE ON public.packing_sessions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_dispatches_updated_at BEFORE UPDATE ON public.dispatches FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_department_requests_updated_at BEFORE UPDATE ON public.department_requests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_material_issue_notes_updated_at BEFORE UPDATE ON public.material_issue_notes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_stock_takes_updated_at BEFORE UPDATE ON public.stock_takes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_stock_take_lines_updated_at BEFORE UPDATE ON public.stock_take_lines FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_cashier_shifts_updated_at BEFORE UPDATE ON public.cashier_shifts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_branch_payments_updated_at BEFORE UPDATE ON public.branch_payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_credit_bills_updated_at BEFORE UPDATE ON public.credit_bills FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_bank_accounts_updated_at BEFORE UPDATE ON public.bank_accounts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER trg_bank_reconciliations_updated_at BEFORE UPDATE ON public.bank_reconciliations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS enablement. Policies should be tightened during API repository cutover.
-- Service role bypasses RLS; anon/authenticated users should go through backend.
-- ---------------------------------------------------------------------------

ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_branch_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.goods_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_outlets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_takes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;

COMMIT;
