-- ============================================================
-- 0022_seed_central_store_inventory.sql
-- Seeds master inventory catalog from the physical stock register.
-- Central store items: branch_id = NULL, store_type per category.
-- ON CONFLICT (sku) DO UPDATE → idempotent / safe to re-run.
-- NOTE: Opening stock is intentionally ignored per user instruction.
-- Duplicate codes in source data handled with suffix (-2).
-- ============================================================

-- Add reorder_description for the text-format reorder notes ("40 bales", "18 pcs" …)
ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS reorder_description TEXT;

-- Rebuild simple_items VIEW to expose reorder_description
DROP VIEW IF EXISTS public.simple_items;
CREATE VIEW public.simple_items AS
SELECT
  id,
  sku,
  sku                   AS item_sku,
  item_name,
  description,
  category,
  category_code,
  unit                  AS unit_of_measure,
  unit,
  default_unit_cost     AS cost_price,
  default_selling_price AS retail_price,
  reorder_level,
  reorder_description,
  is_active,
  store_type,
  branch_id,
  barcode,
  supplier,
  image_url,
  is_auto_sku,
  metadata,
  created_at,
  updated_at,
  quantity,
  last_updated
FROM public.inventory_items;

-- ─────────────────────────────────────────────────────────────
-- SEED DATA
-- Columns: sku, item_name, category, store_type, default_unit_cost,
--          reorder_description, unit, is_active
-- ─────────────────────────────────────────────────────────────
INSERT INTO public.inventory_items
  (sku, item_name, description, category, store_type, default_unit_cost, reorder_description, unit, quantity, is_active)
VALUES
-- ── DRY GOODS ─────────────────────────────────────────────────
('363',   '13KG GAS',                     '13KG GAS',                     'DRY GOODS', 'foodstuffs', 2400.00,  NULL,                 'pcs',  0, true),
('70',    '500ML WATER',                  '500ML WATER',                  'DRY GOODS', 'foodstuffs',   21.00,  NULL,                 'pcs',  0, true),
('151',   '50KG GAS',                     '50KG GAS',                     'DRY GOODS', 'foodstuffs', 1050.00,  NULL,                 'pcs',  0, true),
('157',   '6KG GAS',                      '6KG GAS',                      'DRY GOODS', 'foodstuffs', 1250.00,  NULL,                 'pcs',  0, true),
('153',   '6KGS',                         '6KGS',                         'DRY GOODS', 'foodstuffs',  350.00,  NULL,                 'pcs',  0, true),
('9',     'AIRFRESHERS',                  'AIRFRESHERS',                  'DRY GOODS', 'foodstuffs', 1980.00,  '24+ pcs',            'pcs',  0, true),
('2',     'AJAB UGALI',                   'AJAB UGALI',                   'DRY GOODS', 'foodstuffs',  265.00,  '40 bales',           'pkt',  0, true),
('383',   'ATTARMARK',                    'ATTARMARK',                    'DRY GOODS', 'foodstuffs', 1284.00,  '2 bales 2 pkts',     'pcs',  0, true),
('82',    'BACON',                        'BACON',                        'DRY GOODS', 'foodstuffs',  400.00,  NULL,                 'pkt',  0, true),
('189',   'BAKED BEANS',                  'BAKED BEANS',                  'DRY GOODS', 'foodstuffs',   20.00,  NULL,                 'pcs',  0, true),
('61',    'BAKING POWDER',                'BAKING POWDER',                'DRY GOODS', 'foodstuffs',   10.00,  '1 ctn',              'pcs',  0, true),
('150',   'BANANAS',                      'BANANAS',                      'DRY GOODS', 'foodstuffs',  180.00,  NULL,                 'pcs',  0, true),
('40',    'BARSOAP',                      'BARSOAP',                      'DRY GOODS', 'foodstuffs',   70.00,  '3 ctns',             'pcs',  0, true),
('354',   'BATTERIES AA',                 'BATTERIES AA',                 'DRY GOODS', 'foodstuffs',   50.00,  NULL,                 'pcs',  0, true),
('369',   'BATTERIES AAA',                'BATTERIES AAA',                'DRY GOODS', 'foodstuffs',  850.00,  NULL,                 'pcs',  0, true),
('392',   'BAYGON 24pcs',                 'BAYGON 24pcs',                 'DRY GOODS', 'foodstuffs',  250.00,  NULL,                 'pcs',  0, true),
('339',   'BEEF MASALA',                  'BEEF MASALA',                  'DRY GOODS', 'foodstuffs',  680.00,  '18 pcs',             'pcs',  0, true),
('79',    'BEEF STEAK',                   'BEEF STEAK',                   'DRY GOODS', 'foodstuffs',   32.50,  NULL,                 'pcs',  0, true),
('44',    'BELLA TISSUE',                 'BELLA TISSUE',                 'DRY GOODS', 'foodstuffs',   45.00,  '55 bales',           'pcs',  0, true),
('385',   'BICABORNATE',                  'BICABORNATE',                  'DRY GOODS', 'foodstuffs',   10.00,  '1 ctn',              'pcs',  0, true),
('38',    'BIRO PENS',                    'BIRO PENS',                    'DRY GOODS', 'foodstuffs',  150.00,  '1 ctn / 18 pcs',     'pcs',  0, true),
('46',    'BLACK PEPPER',                 'BLACK PEPPER',                 'DRY GOODS', 'foodstuffs', 2970.00,  '18 pcs',             'pcs',  0, true),
('7',     'BLUE BAND',                    'BLUE BAND',                    'DRY GOODS', 'foodstuffs',   60.00,  '10 dtns',            'pcs',  0, true),
('170',   'BROCOLLI',                     'BROCOLLI',                     'DRY GOODS', 'foodstuffs',   60.00,  NULL,                 'kg',   0, true),
('15',    'BROILERS',                     'BROILERS',                     'DRY GOODS', 'foodstuffs',  600.00,  '100 pcs',            'pcs',  0, true),
('20',    'BROILERS EGGS',                'BROILERS EGGS',                'DRY GOODS', 'foodstuffs',  450.00,  '100 pcs',            'pcs',  0, true),
('370',   'BROOMS',                       'BROOMS',                       'DRY GOODS', 'foodstuffs',   50.00,  NULL,                 'pcs',  0, true),
('111',   'BROWN BREAD',                  'BROWN BREAD',                  'DRY GOODS', 'foodstuffs',   57.00,  NULL,                 'pcs',  0, true),
('352',   'BROWN KIJAKI',                 'BROWN KIJAKI',                 'DRY GOODS', 'foodstuffs',  200.00,  NULL,                 'pcs',  0, true),
('91',    'BUTTERNUT',                    'BUTTERNUT',                    'DRY GOODS', 'foodstuffs',   80.00,  NULL,                 'kg',   0, true),
('32',    'CABBAGES',                     'CABBAGES',                     'DRY GOODS', 'foodstuffs',   45.00,  '100 pcs',            'pcs',  0, true),
('412',   'CAPTAIN MORGAN LEMON 250ML',   'CAPTAIN MORGAN LEMON 250ML',   'DRY GOODS', 'foodstuffs',  384.00,  NULL,                 'pcs',  0, true),
('413',   'CAPTAIN MORGAN LEMON 750ML',   'CAPTAIN MORGAN LEMON 750ML',   'DRY GOODS', 'foodstuffs', 1080.00,  NULL,                 'pcs',  0, true),
('8',     'CARDAMOMS',                    'CARDAMOMS',                    'DRY GOODS', 'foodstuffs',  150.00,  '18 pcs',             'pcs',  0, true),
('341',   'CARRIER BAGS #15',             'CARRIER BAGS #15',             'DRY GOODS', 'foodstuffs',   85.00,  '50 pcs',             'pkt',  0, true),
('351',   'CARRIER BAGS #22',             'CARRIER BAGS #22',             'DRY GOODS', 'foodstuffs',  125.00,  '50 pls',             'pkt',  0, true),
('107',   'CARROTS',                      'CARROTS',                      'DRY GOODS', 'foodstuffs',   30.00,  '140 kgs',            'kg',   0, true),
('109',   'CHARCOAL',                     'CHARCOAL',                     'DRY GOODS', 'foodstuffs', 1450.00,  '10 sacks',           'sack', 0, true),
('77',    'CHICKEN BITES',                'CHICKEN BITES',                'DRY GOODS', 'foodstuffs',  375.00,  '10 pkts',            'pkt',  0, true),
('340',   'CHICKEN MASALA',               'CHICKEN MASALA',               'DRY GOODS', 'foodstuffs',  250.00,  '18 pcs',             'pcs',  0, true),
('124',   'CHILLI SAUCE',                 'CHILLI SAUCE',                 'DRY GOODS', 'foodstuffs',  450.00,  '15 pcs',             'pcs',  0, true),
('344',   'CHILLIE SAUCE SATCHETS',       'CHILLIE SAUCE SATCHETS',       'DRY GOODS', 'foodstuffs',  900.00,  NULL,                 'pkt',  0, true),
('122',   'CINAMON',                      'CINAMON',                      'DRY GOODS', 'foodstuffs',  230.00,  '18 pcs',             'pcs',  0, true),
('59',    'COCONUT CREAM',                'COCONUT CREAM',                'DRY GOODS', 'foodstuffs',  290.00,  '24 pcs',             'pcs',  0, true),
('60',    'COCONUT MILK',                 'COCONUT MILK',                 'DRY GOODS', 'foodstuffs',  285.00,  NULL,                 'pcs',  0, true),
('129',   'COFFEE CUPS',                  'COFFEE CUPS',                  'DRY GOODS', 'foodstuffs',  375.00,  '5 cald',             'pcs',  0, true),
('186',   'COLGATE',                      'COLGATE',                      'DRY GOODS', 'foodstuffs',  800.00,  NULL,                 'pcs',  0, true),
('4',     'COOKING OIL',                  'COOKING OIL',                  'DRY GOODS', 'foodstuffs', 4600.00,  '60 cans',            'can',  0, true),
('76',    'CORN FLOUR',                   'CORN FLOUR',                   'DRY GOODS', 'foodstuffs',  107.00,  '3 ctns',             'pkt',  0, true),
('119',   'CORNFLAKES',                   'CORNFLAKES',                   'DRY GOODS', 'foodstuffs',  350.00,  '10 pkts',            'pkt',  0, true),
('132',   'COTTON',                       'COTTON',                       'DRY GOODS', 'foodstuffs',  200.00,  '12 pks',             'pkt',  0, true),
('185',   'COURGETSY',                    'COURGETSY',                    'DRY GOODS', 'foodstuffs',   40.00,  NULL,                 'kg',   0, true),
('168',   'CUCUMBER',                     'CUCUMBER',                     'DRY GOODS', 'foodstuffs',   40.00,  NULL,                 'pcs',  0, true),
('57',    'CURRY POWDER',                 'CURRY POWDER',                 'DRY GOODS', 'foodstuffs',  250.00,  '18 pcs',             'pcs',  0, true),
('162',   'DANA JEERA',                   'DANA JEERA',                   'DRY GOODS', 'foodstuffs',  215.00,  '12 pcs',             'pcs',  0, true),
('155',   'DANIA',                        'DANIA',                        'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'kg',   0, true),
('63',    'DARKSOY SAUCE',                'DARKSOY SAUCE',                'DRY GOODS', 'foodstuffs',  350.00,  '3 ctns',             'pcs',  0, true),
('187',   'DETTOL',                       'DETTOL',                       'DRY GOODS', 'foodstuffs',  225.00,  '4 Hlts',             'ltr',  0, true),
('393',   'DHANIAY',                      'DHANIAY',                      'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'kg',   0, true),
('93',    'DOOM X',                       'DOOM X',                       'DRY GOODS', 'foodstuffs',  500.00,  NULL,                 'pcs',  0, true),
('407',   'DORMANTS',                     'DORMANTS',                     'DRY GOODS', 'foodstuffs', 1300.00,  '2 ctns',             'pcs',  0, true),
('368',   'DOWNY',                        'DOWNY',                        'DRY GOODS', 'foodstuffs',  500.00,  '60 lts',             'ltr',  0, true),
('12',    'DRINKING CHOCOLATE',           'DRINKING CHOCOLATE',           'DRY GOODS', 'foodstuffs',  100.00,  '1 ctn',              'pcs',  0, true),
('138',   'EASY WARM',                    'EASY WARM',                    'DRY GOODS', 'foodstuffs',  800.00,  '30 pcs',             'pcs',  0, true),
('51',    'EGG YELLOW',                   'EGG YELLOW',                   'DRY GOODS', 'foodstuffs',   60.00,  'cobpac',             'pcs',  0, true),
('166',   'EGGS KIENYEJI',                'EGGS KIENYEJI',                'DRY GOODS', 'foodstuffs',   25.00,  NULL,                 'pcs',  0, true),
('358',   'ENVELOPE A4',                  'ENVELOPE A4',                  'DRY GOODS', 'foodstuffs',   10.00,  NULL,                 'pcs',  0, true),
('359',   'ENVELOPE A5',                  'ENVELOPE A5',                  'DRY GOODS', 'foodstuffs',    5.00,  NULL,                 'pcs',  0, true),
('3',     'EXE ALL PURPOSE',              'EXE ALL PURPOSE',              'DRY GOODS', 'foodstuffs',  155.00,  '20 bales',           'pkt',  0, true),
('390',   'FAMILA WIMBI',                 'FAMILA WIMBI',                 'DRY GOODS', 'foodstuffs',  100.00,  '1 bale',             'pkt',  0, true),
('18',    'FISH',                         'FISH',                         'DRY GOODS', 'foodstuffs',  280.00,  NULL,                 'kg',   0, true),
('145',   'FISH FILLETS',                 'FISH FILLETS',                 'DRY GOODS', 'foodstuffs',  275.00,  '4 kg',               'kg',   0, true),
('58',    'FISH MASALA',                  'FISH MASALA',                  'DRY GOODS', 'foodstuffs',  200.00,  '18 pks',             'pcs',  0, true),
('96',    'FILM',                         'FILM',                         'DRY GOODS', 'foodstuffs',  700.00,  '30 pcs',             'pcs',  0, true),
('97',    'FOIL',                         'FOIL',                         'DRY GOODS', 'foodstuffs', 1400.00,  '20 pcs',             'pcs',  0, true),
('45',    'GARAM MASALA',                 'GARAM MASALA',                 'DRY GOODS', 'foodstuffs',  190.00,  '18 pcs',             'pcs',  0, true),
('92',    'GARLIC',                       'GARLIC',                       'DRY GOODS', 'foodstuffs',   25.00,  '200 pcs',            'pcs',  0, true),
('49',    'GARLIC POWDER',                'GARLIC POWDER',                'DRY GOODS', 'foodstuffs',  180.00,  '18 pcs',             'pcs',  0, true),
('88',    'GINGER',                       'GINGER',                       'DRY GOODS', 'foodstuffs',  250.00,  '20 kgs',             'kg',   0, true),
('48',    'GINGER POWDER',                'GINGER POWDER',                'DRY GOODS', 'foodstuffs',  150.00,  '18 pcs',             'pcs',  0, true),
('366',   'GRAM FLOUR',                   'GRAM FLOUR',                   'DRY GOODS', 'foodstuffs',  450.00,  '2 pkts',             'pkt',  0, true),
('371',   'HAIRNETS',                     'HAIRNETS',                     'DRY GOODS', 'foodstuffs',    1.00,  '200 pcs',            'pcs',  0, true),
('95',    'HAND TOWELS',                  'HAND TOWELS',                  'DRY GOODS', 'foodstuffs',  162.00,  '5 bales',            'pcs',  0, true),
('387',   'HAND WASH',                    'HAND WASH',                    'DRY GOODS', 'foodstuffs',   60.00,  '100 ltrs',           'ltr',  0, true),
('43',    'HANNAN TISSUE',                'HANNAN TISSUE',                'DRY GOODS', 'foodstuffs',   35.00,  '300 pcs',            'pcs',  0, true),
('348',   'HARPIC',                       'HARPIC',                       'DRY GOODS', 'foodstuffs',  160.00,  '20 ltrs',            'ltr',  0, true),
('89',    'HOHO',                         'HOHO',                         'DRY GOODS', 'foodstuffs',   10.00,  '100 pcs',            'pcs',  0, true),
('67',    'HONEY CARTON',                 'HONEY CARTON',                 'DRY GOODS', 'foodstuffs', 2700.00,  '50 ctns',            'ctn',  0, true),
('342',   'HONEY PIECES',                 'HONEY PIECES',                 'DRY GOODS', 'foodstuffs',  150.00,  '20 pcs',             'pcs',  0, true),
('34',    'IDP',                          'IDP',                          'DRY GOODS', 'foodstuffs', 1150.00,  '15 bales',           'pcs',  0, true),
('98',    'JIK',                          'JIK',                          'DRY GOODS', 'foodstuffs',  100.00,  '1000 lts',           'ltr',  0, true),
('160',   'JUICE STRAWS',                 'JUICE STRAWS',                 'DRY GOODS', 'foodstuffs',  180.00,  NULL,                 'pkt',  0, true),
('94',    'JUMBO TISSUE',                 'JUMBO TISSUE',                 'DRY GOODS', 'foodstuffs',  105.00,  'Hoops 20 pcs',       'pcs',  0, true),
('181',   'KAMANDE',                      'KAMANDE',                      'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'kg',   0, true),
('163',   'KETCHUP',                      'KETCHUP',                      'DRY GOODS', 'foodstuffs',  500.00,  NULL,                 'pcs',  0, true),
('22',    'KHAKI PAPERS',                 'KHAKI PAPERS',                 'DRY GOODS', 'foodstuffs',  290.00,  '10 pkts',            'pkt',  0, true),
('108',   'KIENYEJI EGGS',                'KIENYEJI EGGS',                'DRY GOODS', 'foodstuffs',   20.00,  NULL,                 'pcs',  0, true),
('137',   'KITCHEN CLEANER',              'KITCHEN CLEANER',              'DRY GOODS', 'foodstuffs',  240.00,  '5 pcs',              'pcs',  0, true),
('404',   'KITCHEN ROLL',                 'KITCHEN ROLL',                 'DRY GOODS', 'foodstuffs',    0.00,  '1 bale',             'pcs',  0, true),
('37',    'KUKU KIENYEJI',                'KUKU KIENYEJI',                'DRY GOODS', 'foodstuffs',  800.00,  NULL,                 'pcs',  0, true),
('171',   'LEEKS',                        'LEEKS',                        'DRY GOODS', 'foodstuffs',   30.00,  NULL,                 'kg',   0, true),
('175',   'LEMON SQUEZER',                'LEMON SQUEZER',                'DRY GOODS', 'foodstuffs',  500.00,  NULL,                 'pcs',  0, true),
('87',    'LEMONS',                       'LEMONS',                       'DRY GOODS', 'foodstuffs',   80.00,  '200 kgs',            'kg',   0, true),
('169',   'LETTUCE',                      'LETTUCE',                      'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'pcs',  0, true),
('64',    'LIGHT SOY SAUCE',              'LIGHT SOY SAUCE',              'DRY GOODS', 'foodstuffs',  350.00,  '1 ctn',              'pcs',  0, true),
('183',   'MACORONI',                     'MACORONI',                     'DRY GOODS', 'foodstuffs',  350.00,  '50 pkts',            'pkt',  0, true),
('104',   'MANAGU',                       'MANAGU',                       'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'kg',   0, true),
('35',    'MANGOES',                      'MANGOES',                      'DRY GOODS', 'foodstuffs',   40.00,  '100 pcs',            'pcs',  0, true),
('367',   'MARA MOJA',                    'MARA MOJA',                    'DRY GOODS', 'foodstuffs',  100.00,  '10 boxes',           'pcs',  0, true),
('357',   'MARKER PENS',                  'MARKER PENS',                  'DRY GOODS', 'foodstuffs',   30.00,  NULL,                 'pcs',  0, true),
('400',   'MASTER MAIZE MEAL',            'MASTER MAIZE MEAL',            'DRY GOODS', 'foodstuffs',  150.00,  NULL,                 'pkt',  0, true),
('99',    'MATCHBOX',                     'MATCHBOX',                     'DRY GOODS', 'foodstuffs',   26.00,  '1 ctn',              'pcs',  0, true),
('165',   'MATOKE',                       'MATOKE',                       'DRY GOODS', 'foodstuffs',  300.00,  NULL,                 'kg',   0, true),
('416',   'MAYONAISE',                    'MAYONAISE',                    'DRY GOODS', 'foodstuffs',  620.00,  '15 pcs / 900g',      'pcs',  0, true),
('374',   'MAYONNAISE SUPRS',             'MAYONNAISE SUPRS',             'DRY GOODS', 'foodstuffs', 1150.00,  '15 pcs',             'pcs',  0, true),
('149',   'MBUZI',                        'MBUZI',                        'DRY GOODS', 'foodstuffs',  700.00,  NULL,                 'kg',   0, true),
('29',    'MELONS',                       'MELONS',                       'DRY GOODS', 'foodstuffs',  350.00,  NULL,                 'pcs',  0, true),
('406',   'MFALME',                       'MFALME',                       'DRY GOODS', 'foodstuffs',  758.00,  '7 bales',            'pcs',  0, true),
('106',   'MILK PACKET',                  'MILK PACKET',                  'DRY GOODS', 'foodstuffs',  650.00,  '200 ctns',           'ctn',  0, true),
('13',    'MILO SATCHETS',                'MILO SATCHETS',                'DRY GOODS', 'foodstuffs',   20.00,  '1 ctn',              'pcs',  0, true),
('80',    'MINCED MEAT',                  'MINCED MEAT',                  'DRY GOODS', 'foodstuffs',  680.00,  '1 ctn',              'kg',   0, true),
('26',    'MINTS',                        'MINTS',                        'DRY GOODS', 'foodstuffs',  130.00,  NULL,                 'pcs',  0, true),
('169-2', 'MIXED BLUT',                   'MIXED BLUT',                   'DRY GOODS', 'foodstuffs',  550.00,  NULL,                 'pcs',  0, true),
('17',    'MIXED VEGES',                  'MIXED VEGES',                  'DRY GOODS', 'foodstuffs',  180.00,  '5 pkts',             'pkt',  0, true),
('388',   'MOPPERS',                      'MOPPERS',                      'DRY GOODS', 'foodstuffs',  250.00,  NULL,                 'pcs',  0, true),
('345',   'MOZERELA CHEESE',              'MOZERELA CHEESE',              'DRY GOODS', 'foodstuffs', 1250.00,  '1 pkt',              'pkt',  0, true),
('188',   'MULTIPURPOSE DETERGENT',       'MULTIPURPOSE DETERGENT',       'DRY GOODS', 'foodstuffs',   50.00,  '1000 lts',           'ltr',  0, true),
('105',   'MURSIK',                       'MURSIK',                       'DRY GOODS', 'foodstuffs',   80.00,  NULL,                 'ltr',  0, true),
('62',    'MUSHROOM CAN',                 'MUSHROOM CAN',                 'DRY GOODS', 'foodstuffs',  560.00,  '5 pcs',              'pcs',  0, true),
('81',    'MUTTON',                       'MUTTON',                       'DRY GOODS', 'foodstuffs',  680.00,  NULL,                 'kg',   0, true),
('182',   'NDENGU',                       'NDENGU',                       'DRY GOODS', 'foodstuffs',   50.00,  NULL,                 'kg',   0, true),
('36',    'NDUMA',                        'NDUMA',                        'DRY GOODS', 'foodstuffs',  100.00,  '20 pcs',             'pcs',  0, true),
('133',   'NESCAFE',                      'NESCAFE',                      'DRY GOODS', 'foodstuffs',   10.00,  '1 ctn',              'pcs',  0, true),
('184',   'NOTEBOOKS',                    'NOTEBOOKS',                    'DRY GOODS', 'foodstuffs',   35.00,  '1000 pcs',           'pcs',  0, true),
('84',    'ONIONS',                       'ONIONS',                       'DRY GOODS', 'foodstuffs',   65.00,  'Hoops / 1000 pcs',   'kg',   0, true),
('140',   'ORDINARY GLASSES',             'ORDINARY GLASSES',             'DRY GOODS', 'foodstuffs',   65.00,  '6 ctns',             'pcs',  0, true),
('55',    'OREGANO',                      'OREGANO',                      'DRY GOODS', 'foodstuffs',   50.00,  '10 pcs',             'pcs',  0, true),
('50',    'PAPRIKA',                      'PAPRIKA',                      'DRY GOODS', 'foodstuffs',  190.00,  '12 pcs',             'pcs',  0, true),
('31',    'PAWPAW',                       'PAWPAW',                       'DRY GOODS', 'foodstuffs',  130.00,  '4 pcs',              'pcs',  0, true),
('146',   'PEAS',                         'PEAS',                         'DRY GOODS', 'foodstuffs',   70.00,  NULL,                 'kg',   0, true),
('180',   'PEPPER',                       'PEPPER',                       'DRY GOODS', 'foodstuffs',   10.00,  NULL,                 'pcs',  0, true),
('53',    'PILAU MASALA WHOLE',           'PILAU MASALA WHOLE',           'DRY GOODS', 'foodstuffs',   50.00,  '6 pcs',              'pcs',  0, true),
('52',    'PILAU MASALA',                 'PILAU MASALA',                 'DRY GOODS', 'foodstuffs',   50.00,  '12 pcs',             'pcs',  0, true),
('154',   'PILIPILI',                     'PILIPILI',                     'DRY GOODS', 'foodstuffs',  190.00,  NULL,                 'pcs',  0, true),
('30',    'PINEAPPLES',                   'PINEAPPLES',                   'DRY GOODS', 'foodstuffs',  150.00,  '120 pcs',            'pcs',  0, true),
('83',    'PORKCHOPS',                    'PORKCHOPS',                    'DRY GOODS', 'foodstuffs', 1085.00,  '3 pkts',             'pkt',  0, true),
('86',    'POTATOES',                     'POTATOES',                     'DRY GOODS', 'foodstuffs',   50.00,  'Hoops / 1 ctn',      'kg',   0, true),
('373',   'PRESTIGE',                     'PRESTIGE',                     'DRY GOODS', 'foodstuffs',  363.00,  '1 ctn',              'pcs',  0, true),
('389',   'PURE WIMBI',                   'PURE WIMBI',                   'DRY GOODS', 'foodstuffs',  100.00,  '1 ctn',              'pkt',  0, true),
('401',   'REAM',                         'REAM',                         'DRY GOODS', 'foodstuffs',  235.00,  NULL,                 'pcs',  0, true),
('5',     'RICE',                         'RICE',                         'DRY GOODS', 'foodstuffs',   10.00,  '200 kgs',            'kg',   0, true),
('384',   'ROSEMARY LEAVE',               'ROSEMARY LEAVE',               'DRY GOODS', 'foodstuffs',   21.00,  NULL,                 'pcs',  0, true),
('41',    'ROUND SOAPS',                  'ROUND SOAPS',                  'DRY GOODS', 'foodstuffs',  460.00,  '100 pcs',            'pcs',  0, true),
('391',   'ROYCO CUBES',                  'ROYCO CUBES',                  'DRY GOODS', 'foodstuffs',   75.00,  '1 ctn',              'pcs',  0, true),
('375',   'SACKS',                        'SACKS',                        'DRY GOODS', 'foodstuffs',  460.00,  '5 pcs',              'pcs',  0, true),
('343',   'SALT PER 2KG',                 'SALT PER 2KG',                 'DRY GOODS', 'foodstuffs',  568.00,  'H bales',            'pkt',  0, true),
('73',    'SALT SATCHETS',                'SALT SATCHETS',                'DRY GOODS', 'foodstuffs',   60.00,  '4 ctns',             'pkt',  0, true),
('16',    'SAUSAGES',                     'SAUSAGES',                     'DRY GOODS', 'foodstuffs',  160.00,  'Hophs',              'pcs',  0, true),
('28',    'SCRUBBERS',                    'SCRUBBERS',                    'DRY GOODS', 'foodstuffs',  160.00,  '20 pcs',             'pcs',  0, true),
('14',    'SELFRAISING',                  'SELFRAISING',                  'DRY GOODS', 'foodstuffs',  160.00,  '10 bales',           'pkt',  0, true),
('121',   'SERVIETTES',                   'SERVIETTES',                   'DRY GOODS', 'foodstuffs',  260.00,  '20 bales',           'pcs',  0, true),
('42',    'SHOWER GEL',                   'SHOWER GEL',                   'DRY GOODS', 'foodstuffs',  130.00,  '100 pcs',            'pcs',  0, true),
('306',   'SIEVES',                       'SIEVES',                       'DRY GOODS', 'foodstuffs',  130.00,  NULL,                 'pcs',  0, true),
('382',   'SIMPLEX TISSUE',               'SIMPLEX TISSUE',               'DRY GOODS', 'foodstuffs',   25.00,  '10 pkts',            'pkt',  0, true),
('103',   'SKUMA',                        'SKUMA',                        'DRY GOODS', 'foodstuffs',    0.00,  NULL,                 'kg',   0, true),
('78',    'SMOKIES',                      'SMOKIES',                      'DRY GOODS', 'foodstuffs',  427.00,  '10 pcs',             'pcs',  0, true),
('68',    'SODA',                         'SODA',                         'DRY GOODS', 'foodstuffs',  780.00,  NULL,                 'ctn',  0, true),
('173',   'SODA TAKE AWAY',               'SODA TAKE AWAY',               'DRY GOODS', 'foodstuffs', 1480.00,  NULL,                 'ctn',  0, true),
('177',   'SOUP SPOONS',                  'SOUP SPOONS',                  'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'pcs',  0, true),
('90',    'SOUPBOWLS',                    'SOUPBOWLS',                    'DRY GOODS', 'foodstuffs',  250.00,  NULL,                 'pcs',  0, true),
('161',   'SPAGETTI',                     'SPAGETTI',                     'DRY GOODS', 'foodstuffs',  137.50,  '1 ctn',              'pkt',  0, true),
('399',   'SPRING ONIONS',                'SPRING ONIONS',                'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'kg',   0, true),
('356',   'STAFF RICE',                   'STAFF RICE',                   'DRY GOODS', 'foodstuffs',  150.00,  '50 kg',              'kg',   0, true),
('27',    'STAPLE PINS',                  'STAPLE PINS',                  'DRY GOODS', 'foodstuffs',  150.00,  NULL,                 'pcs',  0, true),
('144',   'STRAWBERRY ICECREAM',          'STRAWBERRY ICECREAM',          'DRY GOODS', 'foodstuffs',  280.00,  '12 pkts',            'pkt',  0, true),
('353',   'STRAWS',                       'STRAWS',                       'DRY GOODS', 'foodstuffs',  450.00,  '2 pkts / 5 pkts',    'pkt',  0, true),
('397',   'STUDDED',                      'STUDDED',                      'DRY GOODS', 'foodstuffs',   50.00,  '10 boxes',           'pcs',  0, true),
('1',     'SUGAR KG',                     'SUGAR KG',                     'DRY GOODS', 'foodstuffs',  950.00,  '200 kgs / 1 bale',   'kg',   0, true),
('74',    'SUGARSATCHETS',                'SUGARSATCHETS',                'DRY GOODS', 'foodstuffs',  158.00,  '10 ctns / 1 bale',   'pkt',  0, true),
('347',   'SUPERBRITE',                   'SUPERBRITE',                   'DRY GOODS', 'foodstuffs', 1500.00,  '1 bale',             'pcs',  0, true),
('167',   'SWEETBANANANA',                'SWEETBANANANA',                'DRY GOODS', 'foodstuffs',   10.00,  NULL,                 'pcs',  0, true),
('174',   'T-BONE STEAK',                 'T-BONE STEAK',                 'DRY GOODS', 'foodstuffs',   50.00,  '2 pkts / 5 pkts',    'pcs',  0, true),
('128',   'TAKE AWAY FORKS',              'TAKE AWAY FORKS',              'DRY GOODS', 'foodstuffs',   15.00,  '1 bale',             'pcs',  0, true),
('372',   'TAKE AWAY SPOONS',             'TAKE AWAY SPOONS',             'DRY GOODS', 'foodstuffs', 2075.00,  '1 bale',             'pcs',  0, true),
('21',    'TAKE AWAY TINS',               'TAKE AWAY TINS',               'DRY GOODS', 'foodstuffs',  100.00,  '1 bale',             'pcs',  0, true),
('75',    'TEA BAGS',                     'TEA BAGS',                     'DRY GOODS', 'foodstuffs',  115.00,  '10 boxes',           'pkt',  0, true),
('364',   'TEA FLASK 1 LTR',              'TEA FLASK 1 LTR',              'DRY GOODS', 'foodstuffs',  300.00,  NULL,                 'pcs',  0, true),
('365',   'TEA FLASK 1/2 LTR',            'TEA FLASK 1/2 LTR',            'DRY GOODS', 'foodstuffs', 1500.00,  NULL,                 'pcs',  0, true),
('65',    'TEA MASALA',                   'TEA MASALA',                   'DRY GOODS', 'foodstuffs',  750.00,  '12 pcs / 50 pcs',    'pcs',  0, true),
('172',   'TEALEAVES',                    'TEALEAVES',                    'DRY GOODS', 'foodstuffs',  290.00,  '100 pcs',            'pcs',  0, true),
('33',    'THERMAL ROLLS',                'THERMAL ROLLS',                'DRY GOODS', 'foodstuffs',  180.00,  '50 pcs',             'pcs',  0, true),
('360',   'THUMB TACKS',                  'THUMB TACKS',                  'DRY GOODS', 'foodstuffs',  150.00,  NULL,                 'pcs',  0, true),
('120',   'TOILETBALLS',                  'TOILETBALLS',                  'DRY GOODS', 'foodstuffs',  100.00,  '2 ctns',             'pcs',  0, true),
('11',    'TOMATO PASTE',                 'TOMATO PASTE',                 'DRY GOODS', 'foodstuffs',  125.00,  '12 pcs / 40 pcs',    'pcs',  0, true),
('24',    'TOMATO SAUCE',                 'TOMATO SAUCE',                 'DRY GOODS', 'foodstuffs',  390.00,  '40 pcs',             'pcs',  0, true),
('25',    'TOMATO SAUCE TAKE AWAY',       'TOMATO SAUCE TAKE AWAY',       'DRY GOODS', 'foodstuffs',  400.00,  '10 ctns',            'pcs',  0, true),
('85',    'TOMATOES',                     'TOMATOES',                     'DRY GOODS', 'foodstuffs',  870.00,  '50 kg / 1 case',     'kg',   0, true),
('408',   'TOOTBRUSH',                    'TOOTBRUSH',                    'DRY GOODS', 'foodstuffs',   90.00,  '10 pkts',            'pcs',  0, true),
('349',   'TOOTHBRUSH',                   'TOOTHBRUSH',                   'DRY GOODS', 'foodstuffs',   50.00,  '60 pcs',             'pcs',  0, true),
('350',   'TOOTHPASTE',                   'TOOTHPASTE',                   'DRY GOODS', 'foodstuffs',   30.00,  '10 pkts',            'pcs',  0, true),
('127',   'TOOTHPICKS',                   'TOOTHPICKS',                   'DRY GOODS', 'foodstuffs',   50.00,  '10 pkts',            'pkt',  0, true),
('130',   'TUMBLERS',                     'TUMBLERS',                     'DRY GOODS', 'foodstuffs',  195.00,  '60 pcs / 12 pcs',    'pcs',  0, true),
('54',    'TUMERIC',                      'TUMERIC',                      'DRY GOODS', 'foodstuffs',  124.00,  '10 bales',           'pcs',  0, true),
('398',   'U MIX',                        'U MIX',                        'DRY GOODS', 'foodstuffs',  150.00,  '12 pcs / 1 bale',    'pcs',  0, true),
('394',   'VANILLA ESSENCE',              'VANILLA ESSENCE',              'DRY GOODS', 'foodstuffs',  260.00,  '12 pcs',             'pcs',  0, true),
('19',    'VANILLA ICE CREAM',            'VANILLA ICE CREAM',            'DRY GOODS', 'foodstuffs',  900.00,  '12 pcs',             'pkt',  0, true),
('23',    'VIM',                          'VIM',                          'DRY GOODS', 'foodstuffs',  285.00,  '12 pcs',             'pcs',  0, true),
('126',   'VINEGAR',                      'VINEGAR',                      'DRY GOODS', 'foodstuffs',  380.00,  '12 pcs',             'pcs',  0, true),
('110',   'WEETABIX',                     'WEETABIX',                     'DRY GOODS', 'foodstuffs',  450.00,  '10 boxes',           'pkt',  0, true),
('141',   'WHISKY GLASS',                 'WHISKY GLASS',                 'DRY GOODS', 'foodstuffs',  100.00,  NULL,                 'pcs',  0, true),
('112',   'WHITE BREADE',                 'WHITE BREADE',                 'DRY GOODS', 'foodstuffs',   57.00,  NULL,                 'pcs',  0, true),
('123',   'WHITEPEPPER',                  'WHITEPEPPER',                  'DRY GOODS', 'foodstuffs',  200.00,  '12 pcs',             'pcs',  0, true),
('134',   'WHOLEMEAL',                    'WHOLEMEAL',                    'DRY GOODS', 'foodstuffs',  265.00,  '2 bales',            'pkt',  0, true),
('39',    'WIMBI',                        'WIMBI',                        'DRY GOODS', 'foodstuffs',  200.00,  '2 bales',            'pkt',  0, true),
('136',   'WINDOW CLEANER',               'WINDOW CLEANER',               'DRY GOODS', 'foodstuffs',  255.00,  '12 pcs',             'pcs',  0, true),
('142',   'WINE GLASS',                   'WINE GLASS',                   'DRY GOODS', 'foodstuffs',  230.00,  '36 pcs',             'pcs',  0, true),
('101',   'WIPEX',                        'WIPEX',                        'DRY GOODS', 'foodstuffs',  150.00,  '40 pcs / 1 ctn',     'pcs',  0, true),
('66',    'YEAST',                        'YEAST',                        'DRY GOODS', 'foodstuffs',  130.00,  '1 ctn',              'pcs',  0, true),
('164',   'YELLOW BEANS',                 'YELLOW BEANS',                 'DRY GOODS', 'foodstuffs',   97.71,  '44 kgs',             'kg',   0, true),
('158',   'ZESTAJAM',                     'ZESTAJAM',                     'DRY GOODS', 'foodstuffs',  400.00,  NULL,                 'pcs',  0, true),

-- ── CLEANING MATERIALS ────────────────────────────────────────
('114',   'BOWL MANTAINER 5IN1',          'BOWL MANTAINER 5IN1',          'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'ltr',  0, true),
('118',   'CERAMIC STAIN REMOVER',        'CERAMIC STAIN REMOVER',        'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'ltr',  0, true),
('115',   'GROUT STAIN REMOVER',          'GROUT STAIN REMOVER',          'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'ltr',  0, true),
('117',   'INDUSTRIAL JIK',               'INDUSTRIAL JIK',               'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'ltr',  0, true),
('116',   'SCOURING POWDER',              'SCOURING POWDER',              'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'pcs',  0, true),
('113',   'TOILET DISINFECTANT',          'TOILET DISINFECTANT',          'CLEANING MATERIALS', 'foodstuffs',    0.00, NULL, 'ltr',  0, true),
('176',   'WASHING POWDER',               'WASHING POWDER',               'CLEANING MATERIALS', 'foodstuffs', 1200.00, NULL, 'kg',   0, true),

-- ── BEERS ─────────────────────────────────────────────────────
('190',   'BALOZI',                       'BALOZI',                       'BEERS', 'bar_store', 4225.00, NULL, 'crate', 0, true),
('191',   'BLACK ICE',                    'BLACK ICE',                    'BEERS', 'bar_store', 3982.00, NULL, 'crate', 0, true),
('193',   'GUINNESS',                     'GUINNESS',                     'BEERS', 'bar_store', 5109.00, NULL, 'crate', 0, true),
('196',   'MANYATTA',                     'MANYATTA',                     'BEERS', 'bar_store',  215.00, NULL, 'pcs',   0, true),
('197',   'PILSNER LAGER',                'PILSNER LAGER',                'BEERS', 'bar_store', 4227.00, NULL, 'crate', 0, true),
('199',   'SIKERA',                       'SIKERA',                       'BEERS', 'bar_store', 3275.00, NULL, 'crate', 0, true),
('200',   'SNAPP',                        'SNAPP',                        'BEERS', 'bar_store', 3982.00, NULL, 'crate', 0, true),
('201',   'SUMMIT LAGER',                 'SUMMIT LAGER',                 'BEERS', 'bar_store',  240.00, NULL, 'pcs',   0, true),
('202',   'TUSKER CIDER',                 'TUSKER CIDER',                 'BEERS', 'bar_store', 5552.00, NULL, 'crate', 0, true),
('203',   'TUSKER LAGER',                 'TUSKER LAGER',                 'BEERS', 'bar_store', 4225.00, NULL, 'crate', 0, true),
('204',   'TUSKER LITE',                  'TUSKER LITE',                  'BEERS', 'bar_store', 4667.00, NULL, 'crate', 0, true),
('205',   'TUSKER MALT',                  'TUSKER MALT',                  'BEERS', 'bar_store', 4075.00, NULL, 'crate', 0, true),
('206',   'WHITE CAP LAGER',              'WHITE CAP LAGER',              'BEERS', 'bar_store', 4075.00, NULL, 'crate', 0, true),
('207',   'WHITE CAP LITE',               'WHITE CAP LITE',               'BEERS', 'bar_store', 4075.00, NULL, 'crate', 0, true),

-- ── CANNED BEERS ──────────────────────────────────────────────
('208',   'BALOZI CAN',                   'BALOZI CAN',                   'CANNED BEERS', 'bar_store',  199.20, NULL, 'pcs', 0, true),
('209',   'BLACK ICE CAN',                'BLACK ICE CAN',                'CANNED BEERS', 'bar_store',  175.96, NULL, 'pcs', 0, true),
('211',   'GUINNESS CAN',                 'GUINNESS CAN',                 'CANNED BEERS', 'bar_store',  216.71, NULL, 'pcs', 0, true),
('212',   'PILSNER CAN',                  'PILSNER CAN',                  'CANNED BEERS', 'bar_store',  138.75, NULL, 'pcs', 0, true),
('213',   'SNAPP CAN',                    'SNAPP CAN',                    'CANNED BEERS', 'bar_store',  175.96, NULL, 'pcs', 0, true),
('214',   'TUSKER CIDER CAN',             'TUSKER CIDER CAN',             'CANNED BEERS', 'bar_store',  234.00, NULL, 'pcs', 0, true),
('215',   'TUSKER LAGER CAN',             'TUSKER LAGER CAN',             'CANNED BEERS', 'bar_store',  199.10, NULL, 'pcs', 0, true),
('216',   'TUSKER LITE CAN',              'TUSKER LITE CAN',              'CANNED BEERS', 'bar_store',  243.00, NULL, 'pcs', 0, true),
('217',   'TUSKER MALT CAN',              'TUSKER MALT CAN',              'CANNED BEERS', 'bar_store',  242.00, NULL, 'pcs', 0, true),
('218',   'WHITE CAP CAN',                'WHITE CAP CAN',                'CANNED BEERS', 'bar_store',  242.00, NULL, 'pcs', 0, true),

-- ── ENERGY DRINKS ─────────────────────────────────────────────
('346',   'BEATROOTS',                    'BEATROOTS',                    'ENERGY DRINKS', 'bar_store',   30.00, '24',  'pcs', 0, true),
('219',   'MONSTER',                      'MONSTER',                      'ENERGY DRINKS', 'bar_store',  202.00, NULL,  'pcs', 0, true),

-- ── GIN ───────────────────────────────────────────────────────
('224',   'GORDONS 1LTR',                 'GORDONS 1LTR',                 'GIN', 'bar_store', 1850.00, '50',  'pcs', 0, true),
('225',   'GORDONS 350ML',                'GORDONS 350ML',                'GIN', 'bar_store', 1008.00, '48',  'pcs', 0, true),
('314',   'GORDONS 750ML',                'GORDONS 750ML',                'GIN', 'bar_store', 2000.00, '72',  'pcs', 0, true),

-- ── KWAL ──────────────────────────────────────────────────────
('305',   '4TH STREET SWEET RED',         '4TH STREET SWEET RED',         'KWAL', 'bar_store',  905.00, '18',  'pcs', 0, true),
('243',   'ALL SEASONS 750ML',            'ALL SEASONS 750ML',            'KWAL', 'bar_store', 1080.00, '48',  'pcs', 0, true),
('300',   'AMARULA CREAM 375ML',          'AMARULA CREAM 375ML',          'KWAL', 'bar_store', 1173.00, '6',   'pcs', 0, true),
('301',   'AMARULA CREAM 750ML',          'AMARULA CREAM 750ML',          'KWAL', 'bar_store', 2086.00, '18',  'pcs', 0, true),
('307',   'ASCONI',                       'ASCONI',                       'KWAL', 'bar_store', 1630.00, '12',  'pcs', 0, true),
('246',   'BEST WHISKY 250ML',            'BEST WHISKY 250ML',            'KWAL', 'bar_store',  318.00, '12',  'pcs', 0, true),
('245',   'BEST WHISKY 750ML',            'BEST WHISKY 750ML',            'KWAL', 'bar_store', 1005.00, '12',  'pcs', 0, true),
('334',   'CAMINO BLANCO 750ML',          'CAMINO BLANCO 750ML',          'KWAL', 'bar_store', 2100.00, '12',  'pcs', 0, true),
('335',   'CAMINO REAL GOLD',             'CAMINO REAL GOLD',             'KWAL', 'bar_store', 2300.00, '12',  'pcs', 0, true),
('308',   'CAPRICE SWEET RED',            'CAPRICE SWEET RED',            'KWAL', 'bar_store',  922.00, '12',  'pcs', 0, true),
('323',   'CASABUENA SANGRIA RED',        'CASABUENA SANGRIA RED',        'KWAL', 'bar_store',  922.00, '36',  'pcs', 0, true),
('309',   'CASABUENA SANGRIA WHITE',      'CASABUENA SANGRIA WHITE',      'KWAL', 'bar_store',  755.00, '36',  'pcs', 0, true),
('326',   'CASABUENA SANGRIA WHITE 2',    'CASABUENA SANGRIA WHITE 2',    'KWAL', 'bar_store',  755.00, '36',  'pcs', 0, true),
('306-2', 'CELLAR CASK',                  'CELLAR CASK',                  'KWAL', 'bar_store', 1005.00, '18',  'pcs', 0, true),
('328',   'DELMONTE',                     'DELMONTE',                     'KWAL', 'bar_store', 1005.00, '372', 'pcs', 0, true),
('327',   'DELMONTE (MANGO BLEND)',        'DELMONTE (MANGO BLEND)',        'KWAL', 'bar_store',  242.00, NULL,  'pcs', 0, true),
('330',   'DELMONTE (MIXED BERRY BLEND)', 'DELMONTE (MIXED BERRY BLEND)', 'KWAL', 'bar_store',  242.00, NULL,  'pcs', 0, true),
('329',   'DELMONTE (PASSION BLEND)',      'DELMONTE (PASSION BLEND)',      'KWAL', 'bar_store',  242.00, NULL,  'pcs', 0, true),
('332',   'DELMONTE (PINEAPPLE BLEND)',    'DELMONTE (PINEAPPLE BLEND)',    'KWAL', 'bar_store',  242.00, NULL,  'pcs', 0, true),
('331',   'DELMONTE (TROPICAL BLEND)',     'DELMONTE (TROPICAL BLEND)',     'KWAL', 'bar_store',  242.00, NULL,  'pcs', 0, true),
('192',   'DESPARADO',                    'DESPARADO',                    'KWAL', 'bar_store',  285.00, '72',  'pcs', 0, true),
('311',   'DROSDTY HOF CLARET',           'DROSDTY HOF CLARET',           'KWAL', 'bar_store',  921.00, '18',  'pcs', 0, true),
('322',   'DROSDTY HOF PREMIUM',          'DROSDTY HOF PREMIUM',          'KWAL', 'bar_store', 1750.00, '18',  'pcs', 0, true),
('259',   'FAMOUS GROUSE 750ML',          'FAMOUS GROUSE 750ML',          'KWAL', 'bar_store',  285.00, '12',  'pcs', 0, true),
('210',   'FAXE CAN',                     'FAXE CAN',                     'KWAL', 'bar_store',  825.00, '162', 'pcs', 0, true),
('312',   'FOUR COUSINS RED',             'FOUR COUSINS RED',             'KWAL', 'bar_store',  800.00, '18',  'pcs', 0, true),
('321',   'FOUR COUSINS WHITE',           'FOUR COUSINS WHITE',           'KWAL', 'bar_store',  800.00, '18',  'pcs', 0, true),

-- ── WHISKY ────────────────────────────────────────────────────
('260',   'GLENFIDICH 18YRS 700ML',       'GLENFIDICH 18YRS 700ML',       'WHISKY', 'bar_store', 13100.00, '3',  'pcs', 0, true),
('261',   'GLENFIDICH SINGLE MALT 12YRS', 'GLENFIDICH SINGLE MALT 12YRS', 'WHISKY', 'bar_store',  5925.00, '3',  'pcs', 0, true),
('262',   'GLENFIDICH SINGLE MALT 15YRS', 'GLENFIDICH SINGLE MALT 15YRS', 'WHISKY', 'bar_store',  8550.00, '3',  'pcs', 0, true),
('263',   'GRANTS 1LTR',                  'GRANTS 1LTR',                  'WHISKY', 'bar_store',  1950.00, '24', 'pcs', 0, true),
('264',   'GRANTS 350ML',                 'GRANTS 350ML',                 'WHISKY', 'bar_store',   750.00, '8',  'pcs', 0, true),
('265',   'GRANTS 750ML',                 'GRANTS 750ML',                 'WHISKY', 'bar_store',  1650.00, '24', 'pcs', 0, true),
('194',   'HEINEKEN',                     'HEINEKEN',                     'WHISKY', 'bar_store',   263.00, '192','pcs', 0, true),
('267',   'HENNESSY VSOP 700ML',          'HENNESSY VSOP 700ML',          'WHISKY', 'bar_store',  9200.00, '5',  'pcs', 0, true),
('402',   'HENNESY',                      'HENNESY',                      'WHISKY', 'bar_store',  4600.00, '6',  'pcs', 0, true),
('268',   'HUNTERS CHOICE 250ML',         'HUNTERS CHOICE 250ML',         'WHISKY', 'bar_store',   306.00, '48', 'pcs', 0, true),
('269',   'HUNTERS CHOICE 350ML',         'HUNTERS CHOICE 350ML',         'WHISKY', 'bar_store',   443.00, '36', 'pcs', 0, true),
('270',   'HUNTERS CHOICE 750ML',         'HUNTERS CHOICE 750ML',         'WHISKY', 'bar_store',   938.00, '72', 'pcs', 0, true),
('320',   'HUNTERS CIDER DRY',            'HUNTERS CIDER DRY',            'WHISKY', 'bar_store',   203.00, '72', 'pcs', 0, true),
('195',   'HUNTERS CIDER GOLD',           'HUNTERS CIDER GOLD',           'WHISKY', 'bar_store',   203.00, '72', 'pcs', 0, true),
('282',   'JACK DANIELS 1LTR',            'JACK DANIELS 1LTR',            'WHISKY', 'bar_store',  3300.00, '8',  'pcs', 0, true),
('280',   'JACK DANIELS 350ML',           'JACK DANIELS 350ML',           'WHISKY', 'bar_store',  1650.00, '8',  'pcs', 0, true),
('281',   'JACK DANIELS 700ML',           'JACK DANIELS 700ML',           'WHISKY', 'bar_store',  2800.00, '3',  'pcs', 0, true),
('336',   'JAGERMEISTER 1LTR',            'JAGERMEISTER 1LTR',            'WHISKY', 'bar_store',  3100.00, '6',  'pcs', 0, true),
('337',   'JAGERMEISTER 700ML',           'JAGERMEISTER 700ML',           'WHISKY', 'bar_store',  2200.00, '5',  'pcs', 0, true),
('285',   'JAMESON 1LTR',                 'JAMESON 1LTR',                 'WHISKY', 'bar_store',  3168.00, '12', 'pcs', 0, true),
('283',   'JAMESON 350ML',                'JAMESON 350ML',                'WHISKY', 'bar_store',  1186.00, '10', 'pcs', 0, true),
('284',   'JAMESON 750ML',                'JAMESON 750ML',                'WHISKY', 'bar_store',  2376.00, '12', 'pcs', 0, true),
('315',   'KINGFISHER',                   'KINGFISHER',                   'WHISKY', 'bar_store',   192.00, '72', 'pcs', 0, true),
('333',   'LEMONADE',                     'LEMONADE',                     'WHISKY', 'bar_store',    39.00, '180','pcs', 0, true),
('286',   'MALIBU',                       'MALIBU',                       'WHISKY', 'bar_store',  1713.00, '5',  'pcs', 0, true),
('287',   'MARTEL VS 700ML',              'MARTEL VS 700ML',              'WHISKY', 'bar_store',  4764.00, '6',  'pcs', 0, true),
('288',   'MARTEL VSOP 700ML',            'MARTEL VSOP 700ML',            'WHISKY', 'bar_store',  5800.00, '6',  'pcs', 0, true)

ON CONFLICT (sku) DO UPDATE SET
  item_name           = EXCLUDED.item_name,
  description         = EXCLUDED.description,
  category            = EXCLUDED.category,
  store_type          = EXCLUDED.store_type,
  default_unit_cost   = EXCLUDED.default_unit_cost,
  reorder_description = EXCLUDED.reorder_description,
  unit                = EXCLUDED.unit,
  is_active           = true,
  last_updated        = NOW();
