import 'package:powersync/powersync.dart';

final powerSyncSchema = Schema([
  Table('branches', [
    Column.text('name'),
    Column.text('code'),
    Column.text('location'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('users', [
    Column.text('email'),
    Column.text('role'),
    Column.integer('branch_id'),
    Column.text('first_name'),
    Column.text('last_name'),
    Column.text('active_outlet_id'),
    Column.text('active_outlet_type'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('users_branch_role_idx',
        [IndexedColumn('branch_id'), IndexedColumn('role')]),
  ]),
  Table('notifications', [
    Column.text('user_id'),
    Column.integer('branch_id'),
    Column.text('title'),
    Column.text('message'),
    Column.text('type'),
    Column.text('category'),
    Column.text('priority'),
    Column.integer('is_read'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('notifications_user_idx', [IndexedColumn('user_id')]),
    Index('notifications_branch_idx', [IndexedColumn('branch_id')]),
  ]),
  Table('pos_outlets', [
    Column.integer('branch_id'),
    Column.text('name'),
    Column.text('outlet_type'),
    Column.text('item_group'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_outlets_branch_idx', [IndexedColumn('branch_id')]),
    Index('pos_outlets_type_idx', [IndexedColumn('outlet_type')]),
  ]),
  Table('pos_outlet_assignments', [
    Column.text('user_id'),
    Column.text('outlet_id'),
    Column.integer('branch_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_outlet_assignments_user_idx', [IndexedColumn('user_id')]),
    Index('pos_outlet_assignments_outlet_idx', [IndexedColumn('outlet_id')]),
  ]),
  Table('pos_outlet_items', [
    Column.text('outlet_id'),
    Column.integer('branch_id'),
    Column.text('name'),
    Column.text('category'),
    Column.real('cost_price'),
    Column.real('selling_price'),
    Column.real('current_stock'),
    Column.text('unit'),
    Column.text('item_group'),
    Column.text('item_group_label'),
    Column.text('outlet_name'),
    Column.text('outlet_type'),
    Column.integer('track_stock'),
    Column.integer('is_active'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_outlet_items_outlet_idx', [IndexedColumn('outlet_id')]),
    Index('pos_outlet_items_branch_idx', [IndexedColumn('branch_id')]),
  ]),
  Table('pos_outlet_shifts', [
    Column.text('outlet_id'),
    Column.integer('branch_id'),
    Column.text('cashier_id'),
    Column.text('status'),
    Column.real('opening_float'),
    Column.text('opened_at'),
    Column.text('closed_at'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_outlet_shifts_outlet_idx', [IndexedColumn('outlet_id')]),
    Index('pos_outlet_shifts_cashier_idx', [IndexedColumn('cashier_id')]),
    Index('pos_outlet_shifts_branch_status_idx',
        [IndexedColumn('branch_id'), IndexedColumn('status')]),
  ]),
  Table('pos_shift_orders', [
    Column.text('shift_id'),
    Column.text('outlet_id'),
    Column.integer('branch_id'),
    Column.text('order_number'),
    Column.text('short_code'),
    Column.text('customer_name'),
    Column.text('payment_status'),
    Column.text('status'),
    Column.text('kitchen_status'),
    Column.real('total_amount'),
    Column.text('order_type'),
    Column.text('table_number'),
    Column.text('room_number'),
    Column.real('amount_paid'),
    Column.real('balance_amount'),
    Column.text('waiter_name'),
    Column.integer('is_split'),
    Column.integer('is_merged'),
    Column.integer('is_exchange'),
    Column.text('exchange_parent_order_id'),
    Column.integer('has_active_exchange_request'),
    Column.text('void_request_status'),
    Column.text('captain_printed_at'),
    Column.text('voided_at'),
    Column.text('voided_by'),
    Column.text('void_reason'),
    Column.text('items'),
    Column.integer('bill_reprint_count'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_shift_orders_shift_idx', [IndexedColumn('shift_id')]),
    Index('pos_shift_orders_outlet_idx', [IndexedColumn('outlet_id')]),
    Index('pos_shift_orders_branch_idx', [IndexedColumn('branch_id')]),
  ]),
  Table('pos_shift_payments', [
    Column.text('shift_id'),
    Column.text('order_id'),
    Column.text('payment_method'),
    Column.real('amount'),
    Column.text('reference'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_shift_payments_shift_idx', [IndexedColumn('shift_id')]),
  ]),
  Table('pos_shift_stock_counts', [
    Column.text('shift_id'),
    Column.text('outlet_item_id'),
    Column.text('item_name'),
    Column.text('unit'),
    Column.real('opening_stock'),
    Column.real('additions'),
    Column.real('sold_quantity'),
    Column.real('system_closing_stock'),
    Column.real('physical_count'),
    Column.real('variance'),
    Column.integer('track_stock'),
    Column.text('variance_reason'),
    Column.real('cost_price'),
    Column.real('selling_price'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_shift_stock_counts_shift_idx', [IndexedColumn('shift_id')]),
  ]),
  Table('pos_void_requests', [
    Column.text('shift_id'),
    Column.text('outlet_id'),
    Column.text('order_id'),
    Column.text('order_number'),
    Column.integer('branch_id'),
    Column.text('requested_by'),
    Column.text('reason'),
    Column.text('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('pos_item_void_requests', [
    Column.text('shift_id'),
    Column.text('order_id'),
    Column.integer('item_index'),
    Column.text('item_name'),
    Column.real('unit_price'),
    Column.real('qty_to_void'),
    Column.real('qty_before_void'),
    Column.text('reason_category'),
    Column.text('reason'),
    Column.text('status'),
    Column.text('order_number'),
    Column.integer('branch_id'),
    Column.text('note'),
    Column.text('requested_by'),
    Column.text('requested_by_name'),
    Column.text('actioned_by'),
    Column.text('actioned_by_name'),
    Column.text('cashier_id'),
    Column.text('cashier_name'),
    Column.text('cashier_acknowledged_at'),
    Column.text('cashier_action'),
    Column.text('manager_id'),
    Column.text('manager_name'),
    Column.text('manager_reviewed_at'),
    Column.text('rejection_reason'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_item_void_requests_shift_status_idx',
        [IndexedColumn('shift_id'), IndexedColumn('status')]),
    Index('pos_item_void_requests_branch_status_idx',
        [IndexedColumn('branch_id'), IndexedColumn('status')]),
  ]),
  Table('pos_item_exchange_requests', [
    Column.text('shift_id'),
    Column.text('order_id'),
    Column.text('outlet_id'),
    Column.text('old_items'),
    Column.text('new_items'),
    Column.real('old_total'),
    Column.real('new_total'),
    Column.real('price_difference'),
    Column.text('direction'),
    Column.text('status'),
    Column.text('order_number'),
    Column.integer('branch_id'),
    Column.text('reason'),
    Column.text('requested_by'),
    Column.text('requested_by_name'),
    Column.text('cashier_id'),
    Column.text('cashier_name'),
    Column.text('actioned_at'),
    Column.text('rejection_reason'),
    Column.text('exchange_order_id'),
    Column.real('refund_amount'),
    Column.text('refund_issued_at'),
    Column.text('refund_issued_by'),
    Column.text('refund_issued_by_name'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('pos_item_exchange_requests_shift_status_idx',
        [IndexedColumn('shift_id'), IndexedColumn('status')]),
    Index('pos_item_exchange_requests_branch_status_idx',
        [IndexedColumn('branch_id'), IndexedColumn('status')]),
  ]),
  Table('staff_credit_bills', [
    Column.integer('branch_id'),
    Column.text('staff_id'),
    Column.text('staff_name'),
    Column.text('status'),
    Column.real('total_amount'),
    Column.real('paid_amount'),
    Column.real('balance_amount'),
    Column.text('bill_type'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ], indexes: [
    Index('staff_credit_bills_branch_status_idx',
        [IndexedColumn('branch_id'), IndexedColumn('status')]),
  ]),
  Table('branch_stock', [
    Column.integer('branch_id'),
    Column.text('item_id'),
    Column.text('item_name'),
    Column.real('quantity'),
    Column.text('unit'),
    Column.real('reorder_level'),
    Column.text('updated_at'),
  ], indexes: [
    Index('branch_stock_branch_idx', [IndexedColumn('branch_id')]),
  ]),
  Table('branch_stock_movements', [
    Column.integer('branch_id'),
    Column.text('item_id'),
    Column.text('movement_type'),
    Column.real('quantity'),
    Column.text('reference_id'),
    Column.text('created_at'),
  ], indexes: [
    Index('branch_stock_movements_branch_idx', [IndexedColumn('branch_id')]),
  ]),
]);
