-- Align public bill short codes with the branch-scoped alphanumeric format
-- generated by public.generate_public_short_code():
-- characters 2-9 and A-Z excluding 0, O, I, 1.

-- Re-create the generator function in case 20260526_branch_public_short_codes.sql
-- has not been applied to this database yet (function would otherwise be missing).
CREATE OR REPLACE FUNCTION public.generate_public_short_code(
  p_table REGCLASS,
  p_branch_key TEXT DEFAULT NULL
)
RETURNS TEXT AS $$
DECLARE
  allowed_chars CONSTANT TEXT := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  code_len INTEGER;
  generated_code TEXT;
  code_exists BOOLEAN;
  has_branch_id BOOLEAN;
  i INTEGER;
  attempt INTEGER;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_attribute
    WHERE attrelid = p_table
      AND attname = 'branch_id'
      AND NOT attisdropped
  ) INTO has_branch_id;

  FOR attempt IN 1..100 LOOP
    code_len := CASE WHEN random() < 0.5 THEN 4 ELSE 6 END;
    generated_code := '';

    FOR i IN 1..code_len LOOP
      generated_code := generated_code ||
        substr(allowed_chars, floor(random() * length(allowed_chars) + 1)::INTEGER, 1);
    END LOOP;

    IF has_branch_id THEN
      EXECUTE format(
        'SELECT EXISTS (
           SELECT 1 FROM %s
           WHERE short_code = $1
             AND COALESCE(branch_id::TEXT, '''') = COALESCE($2, '''')
         )',
        p_table
      )
      USING generated_code, p_branch_key
      INTO code_exists;
    ELSE
      EXECUTE format(
        'SELECT EXISTS (SELECT 1 FROM %s WHERE short_code = $1)',
        p_table
      )
      USING generated_code
      INTO code_exists;
    END IF;

    IF NOT code_exists THEN
      RETURN generated_code;
    END IF;
  END LOOP;

  RAISE EXCEPTION 'Unable to generate unique public short code for % after 100 attempts', p_table;
END;
$$ LANGUAGE plpgsql;

UPDATE public.pos_shift_orders
SET short_code = public.generate_public_short_code(
  'public.pos_shift_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.restaurant_orders
SET short_code = public.generate_public_short_code(
  'public.restaurant_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.restaurant_bills
SET short_code = public.generate_public_short_code(
  'public.restaurant_bills'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.bar_orders
SET short_code = public.generate_public_short_code(
  'public.bar_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.pos_transactions
SET short_code = public.generate_public_short_code(
  'public.pos_transactions'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.cashier_bills
SET short_code = public.generate_public_short_code(
  'public.cashier_bills'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';
