-- Fix central store inventory_items: correct names, categories, selling prices
-- and store_type from the authoritative FG STORES price list.
-- KWAL and UDV are distributors, not categories — items are categorised by
-- product type (WHISKY, WINES, SPIRITS, GIN, BEERS, etc.).
-- Only updates rows where data differs.

UPDATE public.inventory_items ii
SET
    item_name             = v.item_name,
    category              = v.category,
    default_selling_price = v.price,
    store_type            = v.store_type,
    updated_at            = NOW()
FROM (VALUES
    -- ── DRY GOODS ────────────────────────────────────────────────────────
    ('FG-1',   'SUGAR KG',                           'DRY GOODS',          128.00, 'foodstuffs'),
    ('FG-2',   'AJAB UGALI',                         'DRY GOODS',         1870.00, 'foodstuffs'),
    ('FG-3',   'EXE ALL PURPOSE',                    'DRY GOODS',          166.00, 'foodstuffs'),
    ('FG-4',   'COOKING OIL',                        'DRY GOODS',         5050.00, 'foodstuffs'),
    ('FG-5',   'RICE',                               'DRY GOODS',          243.00, 'foodstuffs'),
    ('FG-7',   'BLUE BAND',                          'DRY GOODS',         2970.00, 'foodstuffs'),
    ('FG-8',   'CARRIER BAGS #15',                   'DRY GOODS',           85.00, 'foodstuffs'),
    ('FG-9',   'AIRFRESHERS',                        'DRY GOODS',          220.00, 'foodstuffs'),
    ('FG-11',  'TOMATO PASTE',                       'DRY GOODS',          370.00, 'foodstuffs'),
    ('FG-12',  'DRINKING CHOCOLATE',                 'DRY GOODS',           30.00, 'foodstuffs'),
    ('FG-13',  'MILO SATCHETS',                      'DRY GOODS',           20.00, 'foodstuffs'),
    ('FG-14',  'SELFRAISING',                        'DRY GOODS',          165.00, 'foodstuffs'),
    ('FG-15',  'BROILERS',                           'DRY GOODS',          600.00, 'foodstuffs'),
    ('FG-16',  'SAUSAGES',                           'DRY GOODS',          568.00, 'foodstuffs'),
    ('FG-17',  'MIXED VEGES',                        'DRY GOODS',          180.00, 'foodstuffs'),
    ('FG-18',  'FISH',                               'DRY GOODS',          280.00, 'foodstuffs'),
    ('FG-19',  'VANILLA ICE CREAM',                  'DRY GOODS',          970.00, 'foodstuffs'),
    ('FG-20',  'BROILERS EGGS',                      'DRY GOODS',          450.00, 'foodstuffs'),
    ('FG-21',  'TAKE AWAY TINS',                     'DRY GOODS',          115.00, 'foodstuffs'),
    ('FG-22',  'KHAKI PAPERS',                       'DRY GOODS',          290.00, 'foodstuffs'),
    ('FG-23',  'VIM',                                'DRY GOODS',          110.00, 'foodstuffs'),
    ('FG-24',  'TOMATO SAUCE',                       'DRY GOODS',          400.00, 'foodstuffs'),
    ('FG-25',  'TOMATO SAUCE TAKE AWAY',             'DRY GOODS',          870.00, 'foodstuffs'),
    ('FG-26',  'MINTS',                              'DRY GOODS',          204.00, 'foodstuffs'),
    ('FG-27',  'STEELWOOL',                          'DRY GOODS',           20.00, 'foodstuffs'),
    ('FG-28',  'SCRUBBERS',                          'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-29',  'MELONS',                             'DRY GOODS',          350.00, 'foodstuffs'),
    ('FG-30',  'PINEAPLES',                          'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-31',  'PAWPAW',                             'DRY GOODS',          200.00, 'foodstuffs'),
    ('FG-32',  'CABBAGES',                           'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-33',  'THERMAL ROLLS',                      'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-34',  'IDP',                                'DRY GOODS',         1120.00, 'foodstuffs'),
    ('FG-35',  'MANGOES',                            'DRY GOODS',           40.00, 'foodstuffs'),
    ('FG-36',  'NDUMA',                              'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-37',  'KUKU KIENYEJI',                      'DRY GOODS',          800.00, 'foodstuffs'),
    ('FG-38',  'BIRO PENS',                          'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-39',  'WIMBI',                              'DRY GOODS',          266.00, 'foodstuffs'),
    ('FG-40',  'BARSOAP',                            'DRY GOODS',          202.00, 'foodstuffs'),
    ('FG-41',  'ROUND SOAPS',                        'DRY GOODS',           21.00, 'foodstuffs'),
    ('FG-42',  'SHOWER GEL',                         'DRY GOODS',           18.00, 'foodstuffs'),
    ('FG-43',  'HANNAN TISSUE',                      'DRY GOODS',           35.00, 'foodstuffs'),
    ('FG-44',  'BELLA TISSUE',                       'DRY GOODS',           22.00, 'foodstuffs'),
    ('FG-45',  'GARAM MASALA',                       'DRY GOODS',          190.00, 'foodstuffs'),
    ('FG-46',  'BLACK PEPPER',                       'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-48',  'GINGER POWDER',                      'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-49',  'GARLIC POWDER',                      'DRY GOODS',          180.00, 'foodstuffs'),
    ('FG-50',  'PAPRIKA',                            'DRY GOODS',          195.00, 'foodstuffs'),
    ('FG-51',  'EGG YELLOW',                         'DRY GOODS',           21.00, 'foodstuffs'),
    ('FG-52',  'PILAU MASALA',                       'DRY GOODS',          285.00, 'foodstuffs'),
    ('FG-53',  'PILAU MASALA WHOLE',                 'DRY GOODS',          280.00, 'foodstuffs'),
    ('FG-54',  'TUMERIC',                            'DRY GOODS',          176.00, 'foodstuffs'),
    ('FG-55',  'OREGANO',                            'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-57',  'CURRY POWDER',                       'DRY GOODS',          250.00, 'foodstuffs'),
    ('FG-58',  'FISH MASALA',                        'DRY GOODS',          200.00, 'foodstuffs'),
    ('FG-59',  'COCONUT MILK',                       'DRY GOODS',          300.00, 'foodstuffs'),
    ('FG-60',  'COCONUT CREAM',                      'DRY GOODS',          320.00, 'foodstuffs'),
    ('FG-61',  'BAKING POWDER',                      'DRY GOODS',           20.00, 'foodstuffs'),
    ('FG-62',  'MUSHROOM CAN',                       'DRY GOODS',          560.00, 'foodstuffs'),
    ('FG-63',  'DARKSOY SAUCE',                      'DRY GOODS',          325.00, 'foodstuffs'),
    ('FG-64',  'LIGHT SOY SAUCE',                    'DRY GOODS',          300.00, 'foodstuffs'),
    ('FG-65',  'TEA MASALA',                         'DRY GOODS',          290.00, 'foodstuffs'),
    ('FG-66',  'YEAST',                              'DRY GOODS',          275.00, 'foodstuffs'),
    ('FG-67',  'HONEY CARTON',                       'DRY GOODS',         2700.00, 'foodstuffs'),
    ('FG-68',  'SODA',                               'DRY GOODS',          780.00, 'foodstuffs'),
    ('FG-70',  '500ML WATER',                        'DRY GOODS',           41.00, 'foodstuffs'),
    ('FG-73',  'SALT SATCHETS',                      'DRY GOODS',          460.00, 'foodstuffs'),
    ('FG-74',  'SUGARSATCHETS',                      'DRY GOODS',         1500.00, 'foodstuffs'),
    ('FG-75',  'TEA BAGS',                           'DRY GOODS',          300.00, 'foodstuffs'),
    ('FG-76',  'CORN FLOUR',                         'DRY GOODS',          107.00, 'foodstuffs'),
    ('FG-77',  'CHICKEN BITES',                      'DRY GOODS',          375.00, 'foodstuffs'),
    ('FG-78',  'SMOKIES',                            'DRY GOODS',          427.00, 'foodstuffs'),
    ('FG-79',  'BEEF STEAK',                         'DRY GOODS',          680.00, 'foodstuffs'),
    ('FG-80',  'MINCED MEAT',                        'DRY GOODS',          680.00, 'foodstuffs'),
    ('FG-81',  'MUTTON',                             'DRY GOODS',          680.00, 'foodstuffs'),
    ('FG-82',  'BACON',                              'DRY GOODS',         1350.00, 'foodstuffs'),
    ('FG-83',  'PORKCHOPS',                          'DRY GOODS',         1085.00, 'foodstuffs'),
    ('FG-84',  'ONIONS',                             'DRY GOODS',          130.00, 'foodstuffs'),
    ('FG-85',  'TOMATOES',                           'DRY GOODS',           90.00, 'foodstuffs'),
    ('FG-86',  'POTATOES',                           'DRY GOODS',           55.00, 'foodstuffs'),
    ('FG-87',  'LEMONS',                             'DRY GOODS',           80.00, 'foodstuffs'),
    ('FG-88',  'GINGER',                             'DRY GOODS',          200.00, 'foodstuffs'),
    ('FG-89',  'HOHO',                               'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-90',  'SPAGETTI',                           'DRY GOODS',          115.00, 'foodstuffs'),
    ('FG-91',  'BUTTERNUT',                          'DRY GOODS',           80.00, 'foodstuffs'),
    ('FG-92',  'GARLIC',                             'DRY GOODS',           25.00, 'foodstuffs'),
    ('FG-93',  'DOOM',                               'DRY GOODS',         1300.00, 'foodstuffs'),
    ('FG-94',  'JUMBO TISSUE',                       'DRY GOODS',          105.00, 'foodstuffs'),
    ('FG-95',  'HAND TOWELS',                        'DRY GOODS',          162.00, 'foodstuffs'),
    ('FG-96',  'FILM',                               'DRY GOODS',          700.00, 'foodstuffs'),
    ('FG-97',  'FOIL',                               'DRY GOODS',         1400.00, 'foodstuffs'),
    ('FG-98',  'JIK',                                'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-99',  'MATCHBOX',                           'DRY GOODS',           26.00, 'foodstuffs'),
    ('FG-101', 'WIPEX',                              'DRY GOODS',          130.00, 'foodstuffs'),
    ('FG-103', 'SKUMA',                              'DRY GOODS',            0.00, 'foodstuffs'),
    ('FG-104', 'MANAGU',                             'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-105', 'MURSIK',                             'DRY GOODS',           80.00, 'foodstuffs'),
    ('FG-106', 'MILK PACKET',                        'DRY GOODS',          680.00, 'foodstuffs'),
    ('FG-107', 'CARROTS',                            'DRY GOODS',           80.00, 'foodstuffs'),
    ('FG-108', 'KIENYEJI EGGS',                      'DRY GOODS',           20.00, 'foodstuffs'),
    ('FG-109', 'CHARCOAL',                           'DRY GOODS',         1450.00, 'foodstuffs'),
    ('FG-110', 'WEETABIX',                           'DRY GOODS',          450.00, 'foodstuffs'),
    ('FG-111', 'BROWN BREAD',                        'DRY GOODS',           57.00, 'foodstuffs'),
    ('FG-112', 'WHITE BREADE',                       'DRY GOODS',           57.00, 'foodstuffs'),
    ('FG-119', 'CORNFLAKES',                         'DRY GOODS',          350.00, 'foodstuffs'),
    ('FG-120', 'TOILETBALLS',                        'DRY GOODS',          125.00, 'foodstuffs'),
    ('FG-121', 'SERVIETTES',                         'DRY GOODS',           70.00, 'foodstuffs'),
    ('FG-122', 'CINAMON',                            'DRY GOODS',          230.00, 'foodstuffs'),
    ('FG-123', 'WHITEPEPPER',                        'DRY GOODS',          258.00, 'foodstuffs'),
    ('FG-124', 'CHILLI SAUCE',                       'DRY GOODS',          450.00, 'foodstuffs'),
    ('FG-126', 'VINEGAR',                            'DRY GOODS',          380.00, 'foodstuffs'),
    ('FG-127', 'TOOTHPICKS',                         'DRY GOODS',          195.00, 'foodstuffs'),
    ('FG-128', 'TAKA AWAY FORKS',                    'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-129', 'COFFEE CUPS',                        'DRY GOODS',          375.00, 'foodstuffs'),
    ('FG-130', 'TUMBLERS',                           'DRY GOODS',          124.00, 'foodstuffs'),
    ('FG-131', 'SUPERBRITE',                         'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-132', 'COTTON',                             'DRY GOODS',          200.00, 'foodstuffs'),
    ('FG-133', 'NESCAFE',                            'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-134', 'WHOLEMEAL',                          'DRY GOODS',          265.00, 'foodstuffs'),
    ('FG-136', 'WINDOW CLEANER',                     'DRY GOODS',          230.00, 'foodstuffs'),
    ('FG-137', 'KITCHEN CLEANER',                    'DRY GOODS',          240.00, 'foodstuffs'),
    ('FG-138', 'EASY WARM',                          'DRY GOODS',          800.00, 'foodstuffs'),
    ('FG-140', 'ORDINARY GLASSES',                   'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-141', 'WHISKY GLASS',                       'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-142', 'WINE GLASS',                         'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-144', 'STRAWBERRY ICECREAM',                'DRY GOODS',          970.00, 'foodstuffs'),
    ('FG-145', 'FISH FILLETS',                       'DRY GOODS',          275.00, 'foodstuffs'),
    ('FG-146', 'PEAS',                               'DRY GOODS',           70.00, 'foodstuffs'),
    ('FG-149', 'MBUZI',                              'DRY GOODS',          700.00, 'foodstuffs'),
    ('FG-150', 'BANANAS',                            'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-151', '50KG GAS',                           'DRY GOODS',         8500.00, 'foodstuffs'),
    ('FG-153', '6KGS',                               'DRY GOODS',         1250.00, 'foodstuffs'),
    ('FG-154', 'PILIPILI',                           'DRY GOODS',            5.00, 'foodstuffs'),
    ('FG-155', 'DANIA',                              'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-157', '6KG GAS',                            'DRY GOODS',         1050.00, 'foodstuffs'),
    ('FG-158', 'ZESTAJAM',                           'DRY GOODS',          400.00, 'foodstuffs'),
    ('FG-159', 'MIXED BEEF',                         'DRY GOODS',          550.00, 'foodstuffs'),
    ('FG-160', 'JUICE STRAWS',                       'DRY GOODS',          180.00, 'foodstuffs'),
    ('FG-161', 'SPRING ONIONS',                      'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-162', 'DANA JEERA',                         'DRY GOODS',          215.00, 'foodstuffs'),
    ('FG-163', 'KETCHUP',                            'DRY GOODS',          500.00, 'foodstuffs'),
    ('FG-164', 'YELLOW BEANS',                       'DRY GOODS',           70.00, 'foodstuffs'),
    ('FG-165', 'MATOKE',                             'DRY GOODS',          300.00, 'foodstuffs'),
    ('FG-166', 'EGGS KIENYEJI',                      'DRY GOODS',           25.00, 'foodstuffs'),
    ('FG-167', 'SWEETBANANA',                        'DRY GOODS',           15.00, 'foodstuffs'),
    ('FG-168', 'CUCUMBER',                           'DRY GOODS',           40.00, 'foodstuffs'),
    ('FG-169', 'LETTUCE',                            'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-170', 'BROCOLLI',                           'DRY GOODS',           60.00, 'foodstuffs'),
    ('FG-171', 'LEEKS',                              'DRY GOODS',           30.00, 'foodstuffs'),
    ('FG-172', 'TEALEAVES',                          'DRY GOODS',          160.00, 'foodstuffs'),
    ('FG-173', 'SODA TAKE AWAY',                     'DRY GOODS',         1480.00, 'foodstuffs'),
    ('FG-174', 'T-BONE STEAK',                       'DRY GOODS',         2075.00, 'foodstuffs'),
    ('FG-175', 'LEMON SQUEZER',                      'DRY GOODS',          500.00, 'foodstuffs'),
    ('FG-177', 'SOUP SPOONS',                        'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-178', 'SOUPBOWLS',                          'DRY GOODS',          250.00, 'foodstuffs'),
    ('FG-180', 'PEPPER',                             'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-181', 'KAMANDE',                            'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-182', 'NDENGU',                             'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-183', 'MACORONI',                           'DRY GOODS',          350.00, 'foodstuffs'),
    ('FG-184', 'NOTEBOOKS',                          'DRY GOODS',           35.00, 'foodstuffs'),
    ('FG-185', 'COURGETS',                           'DRY GOODS',           40.00, 'foodstuffs'),
    ('FG-186', 'COLGATE',                            'DRY GOODS',          800.00, 'foodstuffs'),
    ('FG-187', 'DETTOL',                             'DRY GOODS',          225.00, 'foodstuffs'),
    ('FG-188', 'MULTIPURPOSE DETERGENT',             'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-189', 'BAKED BEANS',                        'DRY GOODS',          400.00, 'foodstuffs'),
    ('FG-339', 'BEEF MASALA',                        'DRY GOODS',          250.00, 'foodstuffs'),
    ('FG-340', 'CHICKEN MASALA',                     'DRY GOODS',          250.00, 'foodstuffs'),
    ('FG-341', 'CARDAMOMS',                          'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-342', 'HONEY PIECES',                       'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-343', 'SALT PER 2KG',                       'DRY GOODS',           75.00, 'foodstuffs'),
    ('FG-344', 'CHILLIE SAUCE SATCHETS',             'DRY GOODS',          900.00, 'foodstuffs'),
    ('FG-345', 'MOZERELA CHEESE',                    'DRY GOODS',         1250.00, 'foodstuffs'),
    ('FG-347', 'SWEET POTATOES',                     'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-348', 'HARPIC',                             'DRY GOODS',          160.00, 'foodstuffs'),
    ('FG-349', 'TOOTHBRUSH',                         'DRY GOODS',           30.00, 'foodstuffs'),
    ('FG-350', 'TOOTHPASTE',                         'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-351', 'CARRIER BAGS #22',                   'DRY GOODS',          125.00, 'foodstuffs'),
    ('FG-352', 'BROWN KHAKI',                        'DRY GOODS',          200.00, 'foodstuffs'),
    ('FG-353', 'STRAWS',                             'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-354', 'BATTERIES AA',                       'DRY GOODS',           70.00, 'foodstuffs'),
    ('FG-356', 'STAPLE PINS',                        'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-357', 'MARKER PENS',                        'DRY GOODS',           30.00, 'foodstuffs'),
    ('FG-358', 'ENVELOPE A4',                        'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-359', 'ENVELOPE A5',                        'DRY GOODS',            5.00, 'foodstuffs'),
    ('FG-360', 'THUMB TACKS',                        'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-363', '13KG GAS',                           'DRY GOODS',         2400.00, 'foodstuffs'),
    ('FG-364', 'TEA FLASK 1 LTR',                    'DRY GOODS',         1500.00, 'foodstuffs'),
    ('FG-365', 'TEA FLASK 1/2 LTR',                  'DRY GOODS',          750.00, 'foodstuffs'),
    ('FG-366', 'GRAM FLOUR',                         'DRY GOODS',          450.00, 'foodstuffs'),
    ('FG-367', 'MARA MOJA',                          'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-368', 'DOWNY',                              'DRY GOODS',          300.00, 'foodstuffs'),
    ('FG-369', 'BATTERIES AAA',                      'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-370', 'BROOMS',                             'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-371', 'HAIRNETS',                           'DRY GOODS',            1.00, 'foodstuffs'),
    ('FG-372', 'TAKE AWAY SPOONS',                   'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-373', 'PRESTIGE',                           'DRY GOODS',          370.00, 'foodstuffs'),
    ('FG-374', 'MAYONNAISE 5LTRS',                   'DRY GOODS',         1150.00, 'foodstuffs'),
    ('FG-375', 'SACKS',                              'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-382', 'SIMPLEX TISSUE',                     'DRY GOODS',           25.00, 'foodstuffs'),
    ('FG-383', 'ATTARMARK',                          'DRY GOODS',          265.00, 'foodstuffs'),
    ('FG-384', 'ROSEMARY LEAVE',                     'DRY GOODS',           10.00, 'foodstuffs'),
    ('FG-385', 'BICABORNATE',                        'DRY GOODS',           45.00, 'foodstuffs'),
    ('FG-386', 'SIEVES',                             'DRY GOODS',           25.00, 'foodstuffs'),
    ('FG-387', 'HAND WASH',                          'DRY GOODS',           60.00, 'foodstuffs'),
    ('FG-388', 'MOPPERS',                            'DRY GOODS',          250.00, 'foodstuffs'),
    ('FG-389', 'PURE WIMBI',                         'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-390', 'FAMILA WIMBI',                       'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-391', 'ROYCO CUBES',                        'DRY GOODS',          118.00, 'foodstuffs'),
    ('FG-392', 'BAYGON',                             'DRY GOODS',          650.00, 'foodstuffs'),
    ('FG-393', 'DHANIA',                             'DRY GOODS',          100.00, 'foodstuffs'),
    ('FG-394', 'VANILLA ESSENCE',                    'DRY GOODS',          130.00, 'foodstuffs'),
    ('FG-397', 'STUDDED',                            'DRY GOODS',          950.00, 'foodstuffs'),
    ('FG-398', 'U MIX',                              'DRY GOODS',          260.00, 'foodstuffs'),
    ('FG-399', 'STAFF RICE',                         'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-400', 'MASTER MAIZE MEAL',                  'DRY GOODS',          150.00, 'foodstuffs'),
    ('FG-401', 'REAM',                               'DRY GOODS',            0.00, 'foodstuffs'),
    ('FG-404', 'KITCHEN ROLL',                       'DRY GOODS',            0.00, 'foodstuffs'),
    ('FG-406', 'MFALME',                             'DRY GOODS',          758.00, 'foodstuffs'),
    ('FG-407', 'DORMANTS',                           'DRY GOODS',          345.00, 'foodstuffs'),
    ('FG-408', 'TOOTBRUSH',                          'DRY GOODS',           50.00, 'foodstuffs'),
    ('FG-412', 'CAPTAIN MORGAN LEMON FLAVORED 250ML','DRY GOODS',          384.00, 'foodstuffs'),
    ('FG-413', 'CAPTIAN MORGAN LEMON FLAVORED 750 ML','DRY GOODS',        1080.00, 'foodstuffs'),
    ('FG-416', 'MAYONAISE',                          'DRY GOODS',          620.00, 'foodstuffs'),
    -- ── CLEANING MATERIALS ───────────────────────────────────────────────
    ('FG-113', 'TOILET DISINFECTANT',                'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-114', 'BOWL MANTAINER 5IN1',                'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-115', 'GROUT STAIN REMOVER',                'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-116', 'SCOURING POWDER',                    'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-117', 'INDUSTRIAL JIK',                     'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-118', 'CERAMIC STAIN REMOVER',              'CLEANING MATERIALS',   0.00, 'foodstuffs'),
    ('FG-176', 'WASHING POWDER',                     'CLEANING MATERIALS', 1200.00,'foodstuffs'),
    -- ── BEERS ────────────────────────────────────────────────────────────
    ('FG-190', 'BALOZI',                             'BEERS',              250.00, 'bar_store'),
    ('FG-191', 'BLACK ICE',                          'BEERS',              250.00, 'bar_store'),
    ('FG-192', 'DESPARADO',                          'BEERS',              350.00, 'bar_store'),
    ('FG-193', 'GUINNESS',                           'BEERS',              300.00, 'bar_store'),
    ('FG-194', 'HEINEKEN',                           'BEERS',              295.00, 'bar_store'),
    ('FG-195', 'HUNTERS CIDER GOLD',                 'BEERS',              215.00, 'bar_store'),
    ('FG-196', 'MANYATTA',                           'BEERS',              300.00, 'bar_store'),
    ('FG-197', 'PILSNER LAGER',                      'BEERS',              250.00, 'bar_store'),
    ('FG-198', 'SAVANA CIDER',                       'BEERS',              251.00, 'bar_store'),
    ('FG-199', 'SIKERA',                             'BEERS',              250.00, 'bar_store'),
    ('FG-200', 'SNAPP',                              'BEERS',              250.00, 'bar_store'),
    ('FG-201', 'SUMMIT LAGER',                       'BEERS',              300.00, 'bar_store'),
    ('FG-202', 'TUSKER CIDER',                       'BEERS',              250.00, 'bar_store'),
    ('FG-203', 'TUSKER LAGER',                       'BEERS',              250.00, 'bar_store'),
    ('FG-204', 'TUSKER LITE',                        'BEERS',              250.00, 'bar_store'),
    ('FG-205', 'TUSKER MALT',                        'BEERS',              250.00, 'bar_store'),
    ('FG-206', 'WHITE CAP LAGER',                    'BEERS',              250.00, 'bar_store'),
    ('FG-207', 'WHITE CAP LITE',                     'BEERS',              250.00, 'bar_store'),
    ('FG-315', 'KINGFISHER',                         'BEERS',              192.00, 'bar_store'),
    ('FG-320', 'HUNTERS CIDER DRY',                  'BEERS',              203.00, 'bar_store'),
    ('FG-395', 'WINDHOEK',                           'BEERS',              203.00, 'bar_store'),
    -- ── CANNED BEERS ─────────────────────────────────────────────────────
    ('FG-208', 'BALOZI CAN',                         'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-209', 'BLACK ICE CAN',                      'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-210', 'FAXE CAN',                           'CANNED BEERS',       365.00, 'bar_store'),
    ('FG-211', 'GUINNESS CAN',                       'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-212', 'PILSNER CAN',                        'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-213', 'SNAPP CAN',                          'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-214', 'TUSKER CIDER CAN',                   'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-215', 'TUSKER LAGER CAN',                   'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-216', 'TUSKER LITE CAN',                    'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-217', 'TUSKER MALT CAN',                    'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-218', 'WHITE CAP CAN',                      'CANNED BEERS',       300.00, 'bar_store'),
    ('FG-422', 'HEINKEIN CAN',                       'CANNED BEERS',       450.00, 'bar_store'),
    -- ── ENERGY DRINKS ────────────────────────────────────────────────────
    ('FG-219', 'MONSTER',                            'ENERGY DRINKS',      300.00, 'bar_store'),
    ('FG-220', 'RED BULL',                           'ENERGY DRINKS',      200.00, 'bar_store'),
    ('FG-346', 'BEETROOTS',                          'ENERGY DRINKS',       30.00, 'bar_store'),
    -- ── GIN ──────────────────────────────────────────────────────────────
    ('FG-221', 'GILBEYS 250ML',                      'GIN',                600.00, 'bar_store'),
    ('FG-222', 'GILBEYS 350ML',                      'GIN',                800.00, 'bar_store'),
    ('FG-223', 'GILBEYS 750ML',                      'GIN',               1700.00, 'bar_store'),
    ('FG-224', 'GORDONS 1LTR',                       'GIN',               2500.00, 'bar_store'),
    ('FG-225', 'GORDONS 350ML',                      'GIN',               1500.00, 'bar_store'),
    ('FG-314', 'GORDONS 750ML',                      'GIN',               2000.00, 'bar_store'),
    ('FG-242', 'TANGUERAY 10YRS',                    'GIN',               4500.00, 'bar_store'),
    ('FG-294', 'TANGUERAY 750ML',                    'GIN',               4250.00, 'bar_store'),
    ('FG-405', 'TANGUARAY 1 LTR',                    'GIN',               3167.00, 'bar_store'),
    -- ── WHISKY ───────────────────────────────────────────────────────────
    ('FG-243', 'ALL SEASONS 750ML',                  'WHISKY',            1120.00, 'bar_store'),
    ('FG-245', 'BEST WHISKY 750ML',                  'WHISKY',            1005.00, 'bar_store'),
    ('FG-246', 'BEST WHISKY 250ML',                  'WHISKY',             330.00, 'bar_store'),
    ('FG-247', 'BLACK & WHITE 350ML',                'WHISKY',            1000.00, 'bar_store'),
    ('FG-248', 'BLACK & WHITE 750ML',                'WHISKY',            1120.00, 'bar_store'),
    ('FG-410', 'BLACK AND WHITE 1LTR',               'WHISKY',            1548.00, 'bar_store'),
    ('FG-249', 'BOND 7 250ML',                       'WHISKY',             600.00, 'bar_store'),
    ('FG-250', 'BOND 7 350ML',                       'WHISKY',             800.00, 'bar_store'),
    ('FG-251', 'BOND 7 750ML',                       'WHISKY',            1700.00, 'bar_store'),
    ('FG-252', 'CHIVAS REGAL 750ML',                 'WHISKY',            3700.00, 'bar_store'),
    ('FG-253', 'CHIVAS REGAL 1 LTR',                 'WHISKY',            4000.00, 'bar_store'),
    ('FG-259', 'FAMOUS GROUSE 750ML',                'WHISKY',            1950.00, 'bar_store'),
    ('FG-260', 'GLENFIDICH 18YRS 700ML',             'WHISKY',           14950.00, 'bar_store'),
    ('FG-261', 'GLENFIDICH SINGLE MALT 12 YRS',      'WHISKY',            6400.00, 'bar_store'),
    ('FG-262', 'GLENFIDICH SINGLE MALT 15 YRS',      'WHISKY',            9100.00, 'bar_store'),
    ('FG-263', 'GRANTS 1 LTR',                       'WHISKY',            2350.00, 'bar_store'),
    ('FG-264', 'GRANTS 350ML',                       'WHISKY',            1350.00, 'bar_store'),
    ('FG-265', 'GRANTS 750ML',                       'WHISKY',            1800.00, 'bar_store'),
    ('FG-241', 'JACK DANIELS HONEY 750ML',           'WHISKY',            4500.00, 'bar_store'),
    ('FG-271', 'J D HONEY 750ML',                    'WHISKY',            2500.00, 'bar_store'),
    ('FG-272', 'J D HONEY 1 LTR',                    'WHISKY',            3500.00, 'bar_store'),
    ('FG-273', 'J W BLACK 375ML',                    'WHISKY',            1720.00, 'bar_store'),
    ('FG-274', 'J W BLACK 750ML',                    'WHISKY',            3236.00, 'bar_store'),
    ('FG-376', 'J W BLACK 1LTR',                     'WHISKY',            4074.00, 'bar_store'),
    ('FG-377', 'J W BLACK 250ML',                    'WHISKY',            1040.00, 'bar_store'),
    ('FG-411', 'J W BLONDE',                         'WHISKY',            1991.00, 'bar_store'),
    ('FG-279', 'J W GOLD RESERVE',                   'WHISKY',            7000.00, 'bar_store'),
    ('FG-276', 'J W RED 1 LTR',                      'WHISKY',            2237.00, 'bar_store'),
    ('FG-378', 'J W RED 250ML',                      'WHISKY',             560.00, 'bar_store'),
    ('FG-277', 'J W RED 375 ML',                     'WHISKY',             900.00, 'bar_store'),
    ('FG-278', 'J W RED 750ML',                      'WHISKY',            1800.00, 'bar_store'),
    ('FG-275', 'GREEN LABEL 1 LTR',                  'WHISKY',            5500.00, 'bar_store'),
    ('FG-280', 'JACK DANIELS 350ML',                 'WHISKY',            1850.00, 'bar_store'),
    ('FG-281', 'JACK DANIELS 700ML',                 'WHISKY',            2800.00, 'bar_store'),
    ('FG-282', 'JACK DANIELS 1 LTR',                 'WHISKY',            3300.00, 'bar_store'),
    ('FG-283', 'JAMESON 350ML',                      'WHISKY',            1186.00, 'bar_store'),
    ('FG-284', 'JAMESON 750ML',                      'WHISKY',            2376.00, 'bar_store'),
    ('FG-285', 'JAMESON 1 LTR',                      'WHISKY',            3168.00, 'bar_store'),
    ('FG-236', 'KC 250ML',                           'WHISKY',             350.00, 'bar_store'),
    ('FG-237', 'KC 350ML',                           'WHISKY',             500.00, 'bar_store'),
    ('FG-238', 'KC 750ML',                           'WHISKY',            1000.00, 'bar_store'),
    ('FG-290', 'SINGLETON 12 YRS',                   'WHISKY',            5375.00, 'bar_store'),
    ('FG-291', 'SINGLETON 15 YRS',                   'WHISKY',            6584.00, 'bar_store'),
    ('FG-292', 'SINGLETON 18 YRS',                   'WHISKY',            8750.00, 'bar_store'),
    ('FG-295', 'VAT 69 350ML',                       'WHISKY',             800.00, 'bar_store'),
    ('FG-296', 'VAT 69 750ML',                       'WHISKY',            1500.00, 'bar_store'),
    ('FG-297', 'WILLIAM LAWSONS 350ML',              'WHISKY',             869.00, 'bar_store'),
    ('FG-298', 'WILLIAM LAWSONS 750ML',              'WHISKY',            1800.00, 'bar_store'),
    ('FG-299', 'WILLIAM LAWSONS 1 LTR',              'WHISKY',            2229.00, 'bar_store'),
    -- ── SPIRITS ──────────────────────────────────────────────────────────
    ('FG-226', 'RICHOT 250ML',                       'SPIRITS',            600.00, 'bar_store'),
    ('FG-227', 'RICHOT 350ML',                       'SPIRITS',            800.00, 'bar_store'),
    ('FG-228', 'RICHOT 750ML',                       'SPIRITS',           1700.00, 'bar_store'),
    ('FG-229', 'VICEROY 250ML',                      'SPIRITS',            447.00, 'bar_store'),
    ('FG-230', 'VICEROY 375ML',                      'SPIRITS',            653.00, 'bar_store'),
    ('FG-231', 'VICEROY 750ML',                      'SPIRITS',           1260.00, 'bar_store'),
    ('FG-403', 'VICEROY 10YRS',                      'SPIRITS',           3235.00, 'bar_store'),
    ('FG-239', 'KANE EXTRA 250ML',                   'SPIRITS',            350.00, 'bar_store'),
    ('FG-240', 'KANE EXTRA 750ML',                   'SPIRITS',           1000.00, 'bar_store'),
    ('FG-379', 'CAPTAIN MORGAN 250ML',               'SPIRITS',            336.00, 'bar_store'),
    ('FG-380', 'CAPTAIN MORGAN 750ML',               'SPIRITS',            943.00, 'bar_store'),
    ('FG-254', 'DON JOLUO ANEJO',                    'SPIRITS',           7167.00, 'bar_store'),
    ('FG-255', 'DON JOLUO RPSDO',                    'SPIRITS',           5417.00, 'bar_store'),
    ('FG-268', 'HUNTERS CHOICE 250ML',               'SPIRITS',            306.00, 'bar_store'),
    ('FG-269', 'HUNTERS CHOICE 350ML',               'SPIRITS',            443.00, 'bar_store'),
    ('FG-270', 'HUNTERS CHOICE 750ML',               'SPIRITS',           1000.00, 'bar_store'),
    ('FG-293', 'SOUTHERN COMFORT 750ML',             'SPIRITS',           1800.00, 'bar_store'),
    ('FG-286', 'MALIBU',                             'SPIRITS',           1713.00, 'bar_store'),
    ('FG-304', 'V & A 750ML',                        'SPIRITS',            800.00, 'bar_store'),
    ('FG-381', 'V & A 250ML',                        'SPIRITS',            296.00, 'bar_store'),
    ('FG-335', 'CAMINO REAL GOLD',                   'SPIRITS',           2300.00, 'bar_store'),
    ('FG-334', 'CAMINO BLANCO 750ML',                'SPIRITS',           2250.00, 'bar_store'),
    ('FG-289', 'MARTINI BIANCO',                     'SPIRITS',           2200.00, 'bar_store'),
    ('FG-336', 'JAGERMEISTER 1 LTR',                 'SPIRITS',           3100.00, 'bar_store'),
    ('FG-337', 'JAGERMEISTER 700ML',                 'SPIRITS',           2200.00, 'bar_store'),
    -- ── VODKA ────────────────────────────────────────────────────────────
    ('FG-232', 'VODKA 250ML',                        'VODKA',              600.00, 'bar_store'),
    ('FG-233', 'VODKA 350ML',                        'VODKA',             1298.00, 'bar_store'),
    ('FG-234', 'VODKA 750ML',                        'VODKA',             1700.00, 'bar_store'),
    ('FG-235', 'SCOTISH LEADER 750ML',               'VODKA',             2500.00, 'bar_store'),
    -- ── COGNAC ───────────────────────────────────────────────────────────
    ('FG-267', 'HENNESSY VSOP 700ML',                'COGNAC',            9200.00, 'bar_store'),
    ('FG-402', 'HENNESY',                            'COGNAC',            5500.00, 'bar_store'),
    ('FG-287', 'MARTEL VS 700ML',                    'COGNAC',            4764.00, 'bar_store'),
    ('FG-288', 'MARTEL VSOP 700ML',                  'COGNAC',            7865.00, 'bar_store'),
    ('FG-256', 'DOUBLE BLACK 1LTR',                  'COGNAC',            5640.00, 'bar_store'),
    ('FG-257', 'DOUBLE BLACK 750ML',                 'COGNAC',            5374.00, 'bar_store'),
    -- ── LIQUERS ──────────────────────────────────────────────────────────
    ('FG-300', 'AMARULA CREAM 375ML',                'LIQUERS',           1173.00, 'bar_store'),
    ('FG-301', 'AMARULA CREAM 750ML',                'LIQUERS',           2086.00, 'bar_store'),
    ('FG-302', 'BAILEYS 350ML',                      'LIQUERS',           1300.00, 'bar_store'),
    ('FG-303', 'BAILEYS 750ML',                      'LIQUERS',           2300.00, 'bar_store'),
    ('FG-244', 'BEST CREAM 750ML',                   'LIQUERS',           1500.00, 'bar_store'),
    ('FG-319', 'SHERIDANS',                          'LIQUERS',           4500.00, 'bar_store'),
    -- ── WINES ────────────────────────────────────────────────────────────
    ('FG-305', '4TH STREET SWEET RED',               'WINES',              990.00, 'bar_store'),
    ('FG-306', 'CELLAR CASK',                        'WINES',             1005.00, 'bar_store'),
    ('FG-307', 'ASCONI',                             'WINES',             1700.00, 'bar_store'),
    ('FG-308', 'CAPRICE SWEET RED',                  'WINES',              922.00, 'bar_store'),
    ('FG-309', 'CASABUENA SANGRIA RED',              'WINES',              755.00, 'bar_store'),
    ('FG-310', 'CHAMDOR',                            'WINES',              850.00, 'bar_store'),
    ('FG-311', 'DROSDTY HOF CLARET',                 'WINES',              921.00, 'bar_store'),
    ('FG-312', 'FOUR COUSINS RED',                   'WINES',              825.00, 'bar_store'),
    ('FG-313', 'FRONTERA',                           'WINES',             1000.00, 'bar_store'),
    ('FG-316', 'NEDERBURG RED',                      'WINES',             1986.00, 'bar_store'),
    ('FG-317', 'PENASOL',                            'WINES',              850.00, 'bar_store'),
    ('FG-318', 'ROBERTSON SWEET RED',                'WINES',             1000.00, 'bar_store'),
    ('FG-321', 'FOUR COUSINS WHITE',                 'WINES',              800.00, 'bar_store'),
    ('FG-322', 'DROSDTY HOF PREMIUM',                'WINES',              921.00, 'bar_store'),
    ('FG-323', 'CAPRICE SWEET WHITE',                'WINES',              922.00, 'bar_store'),
    ('FG-326', 'CASABUENA SANGRIA WHITE',            'WINES',              755.00, 'bar_store'),
    ('FG-409', 'NEDERBURG WHITE',                    'WINES',             1609.00, 'bar_store'),
    ('FG-243', 'ALL SEASONS 750ML',                  'WHISKY',            1120.00, 'bar_store'),
    -- ── SOFT DRINKS (juices + sodas) ─────────────────────────────────────
    ('FG-327', 'DELMONTE (MANGO BLEND)',             'SOFT DRINKS',        242.00, 'bar_store'),
    ('FG-328', 'DELMONTE',                           'SOFT DRINKS',        265.00, 'bar_store'),
    ('FG-329', 'DELMONTE (PASSION BLEND)',           'SOFT DRINKS',        242.00, 'bar_store'),
    ('FG-330', 'DELMONTE (MIXED BERRY BLEND)',       'SOFT DRINKS',        242.00, 'bar_store'),
    ('FG-331', 'DELMONTE TROPICAL BLEND)',           'SOFT DRINKS',        242.00, 'bar_store'),
    ('FG-332', 'DELMONTE (PINEAPPLE BLEND)',         'SOFT DRINKS',        242.00, 'bar_store'),
    ('FG-333', 'LEMONADE',                           'SOFT DRINKS',         39.00, 'bar_store'),
    ('FG-414', 'SODA CH',                            'SOFT DRINKS',          0.00, 'bar_store'),
    ('FG-415', 'TAKE AWAY SODA',                     'SOFT DRINKS',          0.00, 'bar_store'),
    ('FG-417', 'WATER 1LTR',                         'SOFT DRINKS',         41.00, 'bar_store'),
    ('FG-418', 'WATER 5OOML',                        'SOFT DRINKS',         21.00, 'bar_store'),
    ('FG-419', 'SODA TAKE AWAY 500ML',               'SOFT DRINKS',         60.00, 'bar_store'),
    ('FG-420', 'SODA 300ML',                         'SOFT DRINKS',         31.00, 'bar_store'),
    ('FG-421', 'WATER 10LTR',                        'SOFT DRINKS',         86.00, 'bar_store')
) AS v(sku, item_name, category, price, store_type)
WHERE ii.sku = v.sku
  AND (
      ii.item_name IS DISTINCT FROM v.item_name
      OR ABS(COALESCE(ii.default_selling_price, 0) - v.price) > 0.009
      OR COALESCE(ii.category, '') IS DISTINCT FROM v.category
      OR COALESCE(ii.store_type, '') IS DISTINCT FROM v.store_type
  );
