-- Align public bill short codes with the branch-scoped alphanumeric format
-- generated by public.generate_public_short_code():
-- characters 2-9 and A-Z excluding 0, O, I, 1.

UPDATE public.pos_shift_orders
SET short_code = public.generate_public_short_code(
  'public.pos_shift_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.restaurant_orders
SET short_code = public.generate_public_short_code(
  'public.restaurant_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.restaurant_bills
SET short_code = public.generate_public_short_code(
  'public.restaurant_bills'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.bar_orders
SET short_code = public.generate_public_short_code(
  'public.bar_orders'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.pos_transactions
SET short_code = public.generate_public_short_code(
  'public.pos_transactions'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';

UPDATE public.cashier_bills
SET short_code = public.generate_public_short_code(
  'public.cashier_bills'::regclass,
  COALESCE(branch_id::text, '')
)
WHERE short_code IS NOT NULL
  AND short_code ~ '^[0-9]{4,6}$';
