-- Cashier logbooks generated by the active cashier desk flow must link to
-- cashier_shift_logs, not the legacy cashier_shifts table.

ALTER TABLE IF EXISTS public.cashier_logbooks
  ADD COLUMN IF NOT EXISTS cashier_shift_id UUID;

DO $$
DECLARE
  constraint_name text;
BEGIN
  FOR constraint_name IN
    SELECT c.conname
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY(c.conkey)
    WHERE t.relname = 'cashier_logbooks'
      AND c.contype = 'f'
      AND a.attname = 'cashier_shift_id'
  LOOP
    EXECUTE format('ALTER TABLE public.cashier_logbooks DROP CONSTRAINT %I', constraint_name);
  END LOOP;
END $$;

ALTER TABLE IF EXISTS public.cashier_logbooks
  ADD CONSTRAINT cashier_logbooks_cashier_shift_id_fkey
  FOREIGN KEY (cashier_shift_id)
  REFERENCES public.cashier_shift_logs(id)
  ON DELETE SET NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_cashier_logbooks_cashier_shift
  ON public.cashier_logbooks(cashier_shift_id)
  WHERE cashier_shift_id IS NOT NULL;
